### ISSUE TITLE
Localization issue with 2.0 preview

### ISSUE THREAD

**Issue by joncrain** [swiftDialog/swiftDialog#173]
Apologies if you don't want issues for the 2.0 release here yet.

I noticed when testing my script, the `alignment` (now `messagealignment`) to longer respects "center" and instead only works with "centre".
It would be great to also have `alignment` continue to work as well, but I understand if that's just a change that needs to be made going forward.

**Comment by bartreardon** [comment]
This should be fixed in the latest release - LMK if it's still an issue

**Comment by bartreardon** [comment]
closing as fixed
