### ISSUE TITLE
Markdown inline images do not support paths to local image files, only http[s] urls

### ISSUE THREAD

**Issue by glenfarclas17** [swiftDialog/swiftDialog#196]
I just downloaded v2.0 to start playing around with swiftDialog - thanks for the amazing work!

I just wanted to report this issue I found pretty quickly:

The CommonMark Spec seems to indicate that the source for inline images can be a local file, and a [relative](https://spec.commonmark.org/0.30/#example-577) or [absolute](https://spec.commonmark.org/0.30/#example-578) path can be used.  However when I try this

```
dialog --title 'Helllo World' --message "\![foo](/path/to/a/local/file.png)" 
```

or a multiline version 

```
read -r -d '' msg <<'EOF'
This is the line _above_ the image  
![foo](/path/to/a/local/file.png)  
This is the line **below** the image
EOF

dialog --title 'Helllo World' --message "$msg" 
```

The image is never shown. 

Allowing this would let me use markdown to have both a message and an image at the same time.

Thanks so much!
-Chris

**Comment by bartreardon** [comment]
correct - that's a limitation in MarkdownUI for reading images that are not inside the application bundle

https://github.com/gonzalezreal/MarkdownUI/issues/46

It's something that I'm actively looking at though to see if there's a workaround which at this stage looks like either alternates to MarkdownUI, or implement built in markdown support if running on macOS 12 or newer

**Comment by glenfarclas17** [comment]
Ahh I was wondering if it was an issue in the markdown lib or not - thanks for responding and I hope a workaround is easy to find and implement.

Cheers,
-Chris

**Comment by mm2270** [comment]
@glenfarclas17 You beat me to posting this. I found the same thing when playing around with adding images using Marrkdown. I'm glad I'm not the only one that would find it useful to be able to use a local image file path in this way. It would actually somewhat satisfy the FR I just posted earlier today. See Issue #194

**Comment by bartreardon** [comment]
closing as I don't think this is going to be resolved within markdownUI
