### ISSUE TITLE
Is it possible to add a transition button or like behaviour to existing buttons?

### ISSUE THREAD

**Issue by stegray93** [swiftDialog/swiftDialog#200]
It'd be great if we could have an option which prevents buttons from exiting dialog and acts like a next button, then we can continue to update the dialog via the command file and make smooth transitions. 

Currently the behaviour closes the app and re-opens it with whatever the next set of variables you want to pass. Essentially I'm looking for a smooth transition between a series of dialog screens if possible. 

Thank you 👍

**Comment by bartreardon** [comment]
yup - this is similar/the same as this request https://github.com/bartreardon/swiftDialog/issues/70

It's something I'll be looking at. The end goal of the refactor performed between v1 and v2 is to actually allow something along these lines.

Technically it's possible now (as in how the code works, not with the released version), the only issue is getting the action of clicking "Next" and working out what to do from there. I have some ideas I'm playing with.

**Comment by stegray93** [comment]
Great, thank you so much for all your hard work.

**Comment by bartreardon** [comment]
probably not in my radar for a while so I'm going to close this as a wontfix

In the meantime, with the updated management of `--ontop` and `--blurscreen` when using multiple dialogs, a similar effect (from a UX point of view) can be done with some careful scripting. I've posted an example here which can be expanded on or pulled apart as needed.

https://github.com/bartreardon/swiftDialog-scripts/tree/main/MultiDialog
