### ISSUE TITLE
Window position issue when connecting/disconnecting external monitor

### ISSUE THREAD

**Issue by mobofixer** [swiftDialog/swiftDialog#209]
I am using a MacBook Pro with an External Monitor:
**Starting with monitor plugged in**: 
When `/usr/local/bin/dialog -t test` is invoked & set to `--position center` the window is positioned in the center.
- when I unplug the monitor the window then locks to the top right of the screen and cuts off the action button
- plugging the monitor back in relocates it to the center or sometimes to relocates it to the bottom left

**Starting with the monitor unplugged**: 
When `/usr/local/bin/dialog -t test` is invoked & set to `--position center` the window is positioned in the center.
- when I plug the monitor in, the window shifts down and to the left
- unplugging the monitor relocates the window to the center on the Macbook screen

**Comment by bartreardon** [comment]
What's the use case for addressing this issue?

The window position code uses the screen layout as it existed at launch to determine where to position the window on the screen. If you change the screen layout by adding or removing an external display or changing the screen resolution it will not update the internal logic that has determined what and how many screens you have.

I'd consider this an edge case.

**Comment by mobofixer** [comment]
you can close this out as it is an edge case.
