### ISSUE TITLE
Result of command: Notifications are not available: Couldn’t communicate with a helper application.

### ISSUE THREAD

**Issue by fillie86** [swiftDialog/swiftDialog#219]
Hi everyone, i am currently seeing this issue inside the jamf logs:

Result of command:
Notifications are not available: Couldn’t communicate with a helper application.

I am pushing the alert.mobileconfig, so it should work. What could be wrong?

**Comment by Alitejawi** [comment]
Are you running the dialog command as the user? Have you checked this: https://github.com/bartreardon/swiftDialog/wiki/Notifications#alert-mobileconfig

**Comment by acodega** [comment]
You'll want to run swiftDialog as the logged in user, with a function like this: https://scriptingosx.com/2020/08/running-a-command-as-another-user/

The 2.1.0 RC1 has an updated launcher so you don't have to run swiftDialog as the logged in user, so that will be out of beta soon. https://github.com/bartreardon/swiftDialog/releases

**Comment by fillie86** [comment]
> Are you running the dialog command as the user? Have you checked this: https://github.com/bartreardon/swiftDialog/wiki/Notifications#alert-mobileconfig

I am using the Files and Processes -> execute command with Jamf Pro. 



> You'll want to run swiftDialog as the logged in user, with a function like this: https://scriptingosx.com/2020/08/running-a-command-as-another-user/
> 
> The 2.1.0 RC1 has an updated launcher so you don't have to run swiftDialog as the logged in user, so that will be out of beta soon. https://github.com/bartreardon/swiftDialog/releases

Could you please tell me how to do that?

**Comment by fillie86** [comment]
I tried to push the 2.1.0 RC1 but i receive the same error. What could be the issue?

**Comment by bartreardon** [comment]
> I am using the Files and Processes -> execute command with Jamf Pro.

What's the full command that you're putting in here?

**Comment by fillie86** [comment]
> > I am using the Files and Processes -> execute command with Jamf Pro.
> 
> What's the full command that you're putting in here?

dialog --notification --title "MY TITLE" --message "MY MESSAGE" --icon "/ICONPATH.PNG"

**Comment by bartreardon** [comment]
> dialog --notification --title "MY TITLE" --message "MY MESSAGE" --icon "/ICONPATH.PNG"

ok, that isn't going to work pre v2.1. the notification needs to run as the user and when you run a command with "Files and Processes" it runs at a system level (root but not really) which does not have the ability to receive system notifications.

can you double check the dialog launcher for me: `wc -l $(which dialog) ` - if you've installed 2.1 RC1 or RC2 this should have 28 lines

**Comment by fillie86** [comment]
28 yes

> > dialog --notification --title "MY TITLE" --message "MY MESSAGE" --icon "/ICONPATH.PNG"
> 
> ok, that isn't going to work pre v2.1. the notification needs to run as the user and when you run a command with "Files and Processes" it runs at a system level (root but not really) which does not have the ability to receive system notifications.
> 
> can you double check the dialog launcher for me: `wc -l $(which dialog) ` - if you've installed 2.1 RC1 or RC2 this should have 28 lines

28 exactly

**Comment by shannonpasto** [comment]
Hi.
I'm seeing this error as well (v2.1.0.4148) but not on all Macs. I have tried launching dialog with `/usr/local/bin/dialog --notification --title TITLE --message MESSAGE` and `/bin/launchctl asuser "${CurrentlyLoggedInUserUID}" "/Library/Application Support/Dialog/Dialog.app/Contents/MacOS/Dialog --notification --title TITLE --message MESSAGE"` I've even tried pre-launching Dialog.app `/bin/launchctl asuser "${CurrentlyLoggedInUserUID}" "/Library/Application Support/Dialog/Dialog.app` as that was something I found when Googling. I have a notifications payload deployed with critical alerts turned off. 

Any ideas?
Shannon

**Comment by bartreardon** [comment]
in 2.1+ just run `/usr/local/bin/dialog`

don't worry about trying to determine the user, fiddling with `launchctl asuser` etc - the updated dialog launcher handles that.

I have a test notification policy and this works fine for sending the notification:

![image](https://user-images.githubusercontent.com/3598965/218361171-fe4a0916-7413-47fb-99e9-2b173cd0c89e.png)

**Comment by shannonpasto** [comment]
That's how I have it currently. The script is running as part of a check-in policy in Jamf
```
#!/bin/sh
sD="/usr/local/bin/dialog"
"${sD}" --notification --title "TITLE" --message "MESSAGE"

**Comment by dan-snelson** [comment]
On the off-chance the following proves helpful:
https://snelson.us/2023/03/custom-branded-notifications-messages-with-swiftdialog/

**Comment by tslucas** [comment]
Same issue on Mosyle MDM using both a notification profile via Mosyle and the custom profile provided in the wiki. Tried running command as user as well. No dice

28 lines

**Comment by acodega** [comment]
He can recreate this, noticing it this week. Kandji, swiftDialog 2.2.1.4591, Ventura 13.2.1 and 13.4.1 (c). Using banner or alert config profile, profile installed before swiftDialog is.

Simple command like ```#!/bin/bash

/usr/local/bin/dialog --notification --title "TITLE" --message "MESSAGE"```

**Comment by acodega** [comment]
This now appears fixed when testing with the [2.3.0 Beta 2](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0-4707)!

**Comment by bartreardon** [comment]
should be fixed in the release version of [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0)

**Comment by acodega** [comment]
Notifications are working for me on 2.3.1. MDM Kandji, Alerts config profile in place. I would like to hear input from others.

**Comment by bartreardon** [comment]
closing this as fixed - if there's any issues, LMK and I can re-open
