### ISSUE TITLE
Default button response in 2.1.0.4148

### ISSUE THREAD

**Issue by mm2270** [swiftDialog/swiftDialog#223]
Hey @bartreardon Thanks for getting this 2.1 release out! So many cool new features in this version now. I'm loving it!

I did want to drop here though, that in some basic tests with it so far, one thing that your notes mentioned was fixed, doesn't seem to be working for me. Specifically, this item:

`• Fixes an issue when a message is being displayed that causes the default button to not initially respond to a press of the {Enter} key.`

Using the 2.1.0.4148 release, so far my tests have all resulted in the same behavior as before. The default button requires a double Return or Enter before its activated. I thought at first it was due to one of the new features like the `--infobox` or the `--helpmessage`, but even doing a very basic dialog like `dialog --message "Hello" --ontop`, the default button does not respond for me on the first hit of Return/Enter.

In case this helps at all, what I see is the cursor is at first visible over the dialog or near it, then when I hit Return the cursor disappears. Then on the next press of Return it dismisses the dialog.

It's not a huge deal, but it would be lovely to really have that fixed. It is a slight bit annoying.

I'm happy to test out anything you might suggest or come back with. I'm also curious if anyone else is still seeing that, or if it's just me.

**Comment by bartreardon** [comment]
hmm - I'm not seeing that behaviour here

Can I get you to verify what version you're running with `dialog --version` and also post an example command where this issue manifests.

**Comment by bartreardon** [comment]
also can you let me know what os version, language and keyboard layout you are using?

**Comment by mm2270** [comment]
Hi @bartreardon Sure.

So, all of the Macs (2 of them so far) I've tested this on are running macOS Monterey, 12.6.2 or 12.6.3.
Both Macs are Intel models. I do have access to an M1 MacBook Pro I can test it with if you think that makes any difference.
Both Macs are running the standard US keyboard layout and using US English.

As for the version:
```
% dialog --version                            
2.1.0.4148
```
Same for both Macs.

Here's a simple command run direct from Terminal that exhibits this behavior on both systems.
```
/usr/local/bin/dialog --message "This is a message"
```
The behavior is that, first press of Return, the cursor disappears. Second press, the dialog is dismissed.
I've tried adding in and/or removing flags, but none of the other options seem to affect this one way or the other for me.

I haven't tested this yet by running it from a Jamf policy. I can do that as a last check to see if somehow the behavior is different, but I'd be surprised if it affected anything in regards to this.

Thanks, and please let me know if you need any more info or want me to test anything.

**Comment by bartreardon** [comment]
this should be fixed - LMK if it's still aproblem and I can re-open
