### ISSUE TITLE
Application Focus inconsistent when using 'return' vs. clicking 'ok'

### ISSUE THREAD

**Issue by BigMacAdmin** [swiftDialog/swiftDialog#228]
This is a very minor thing, but wanted to draw your attention in case it brings something else to light.

When the "OK" button is clicked via mouse, Dialog will exit and the application focus will return to whichever application was active prior to the Dialog window being drawn.

When the "Return/Enter" key is used to dismiss a window the user's application focus is always set to Finder. If there is a Finder window open behind other windows, it will bring this Finder window to the forefront.

Steps to reproduce:

1. Open an application like Chrome or Safari
2. Open Terminal.app
3. Call a dialog window after a brief sleep: `sleep 3; dialog -t test -m message`
4. During that 3 second sleep, switch focus to your other application
5. Click "OK" button, and your desired Application will return in focus
6. Repeat from step 3, but this time use Return/Enter to dismiss the dialog
7. You will have Finder as your active application

**Comment by BigMacAdmin** [comment]
I'm unable to recreate this after a reboot, so maybe there was something funky going on with my user session. Please test and see if you can recreate, sorry to waste your time if not.

**Comment by bartreardon** [comment]
yeah - I can't seem to replicate this behaviour

**Comment by mm2270** [comment]
I can't replicate this either FWIW.

**Comment by bartreardon** [comment]
@BigMacAdmin How's your experience been since reporting the issue? LMK if it's come back.

**Comment by BigMacAdmin** [comment]
I am still experiencing this anomaly. Not a game breaking problem but an oddity.

**Comment by bartreardon** [comment]
should be fixed with the updated way swiftdialog is launched in 2.3.1

I can re-open if this is still a problem but I was unable to replicate it with the latest version
