### ISSUE TITLE
Feature request: Ability to play video or add web content to running dialog via dialog.log

### ISSUE THREAD

**Issue by geekquixotic** [swiftDialog/swiftDialog#229]
This is already so far ahead of other tools we use for automated enrollment workflows that I'm dragging my colleagues over here if I have to do it by force.

At this time however, there are two features of "that other" notification tool that we use that dialog doesn't have... yet.

Could you please add the ability to add a video and/or display web content within a running dialog through the /var/tmp/dialog.log file?

**Comment by bp88** [comment]
This would be nice to see implemented. At the moment, you can't really update the view with web content. You need to have opened the dialog window with web content to start with.

**Comment by bartreardon** [comment]
ooh, thanks for the reminder.

**Comment by bartreardon** [comment]
initial attempt available in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0) (missed the release notes though)

`echo "webcontent: https://some.website.com" >> /var/tmp/dialog.log`
`echo "video: https://some.website.com/video.mov" >> /var/tmp/dialog.log`
`echo "video: /path/to/file.mov" >> /var/tmp/dialog.log`

Some caveats though:
Currently you can't update web or video content in place. To switch to another website you will need to clear the contents and then send the new content.

`echo "webcontent: none" >> /var/tmp/dialog.log`
`echo "webcontent: https://some.new.website.com" >> /var/tmp/dialog.log`

you can string those together though so `echo "webcontent: none" >> /var/tmp/dialog.log && echo "webcontent: https://some.new.website.com" >> /var/tmp/dialog.log` works fine.

Let me know what you think.

**Comment by bartreardon** [comment]
closing as implemented. If there's any tweaks or issues I'll track those under a new issue
