### ISSUE TITLE
Feature Request: showDelayOptions

### ISSUE THREAD

**Issue by Tribruin** [swiftDialog/swiftDialog#234]
I would really like to move away from Jamf Helper to Swift Dialog, but there is one feature of Jamf Helper that is a huge part of my toolkit, the `-showDelayOptions` argument. It is nice to be able to enter a list of times in seconds and have the drop down intelligently convert in to mins, hours, and days. 

Thanks for the consideration.

**Comment by bartreardon** [comment]
Thanks for the suggestion.

No plans to implement at this time. The rule I try to keep for features is that swiftDialog functions are generalised and the intelligence comes from the script calling it. This allows for the greatest flexibility in how it is used.

You can populate a select list with values and then perform processing based on the result. This is why I output the index of the value selected as well as the text.

e.g. The following will give you the index of the selected option

`selected=$(dialog --selecttitle "Delay" --selectvalues "1 Minute, 5 Minutes, 10 Minutes" | grep "SelectedIndex" | awk -F " : " '{print $NF}')`

and you can use the returned result to look up what the selected index means. This is obviously greatly simplified and intended to be a starting point but should illustrate what I mean.

This is not a "no, not ever" answer, but what you want to do it not impossible to achieve with swiftDialog as it currently is.

**Comment by BigMacAdmin** [comment]
https://github.com/SecondSonConsulting/swiftDialogExamples/blob/main/deferralsExample.sh

Hi @Tribruin you may find this template/example useful as a starting point or inspiration.

**Comment by bartreardon** [comment]
closing as wontfix
