### ISSUE TITLE
Wiki Page Update

### ISSUE THREAD

**Issue by aanklewicz** [swiftDialog/swiftDialog#249]
Wanted to edit the wiki page for Window Size and Behaviour
https://github.com/bartreardon/swiftDialog/wiki/Window-Size-and-Behaviour

There doesn't seem to be an edit button, so I thought I'd post the section I wanted to add here.

### Blur Screen
Dialog can blur the screen around the Dialog window, making the rest of the user's desktop inaccessible. 

`--blurscreen` can be used to accomplish this. 

![Screenshot 2023-03-31 at 7 21 05 AM](https://user-images.githubusercontent.com/8291873/229149297-ab060e52-120a-42bc-8a4c-1150b7d80ca2.png)

**Comment by bartreardon** [comment]
updated - I used some different wording but used your screenshot example 🙂 

https://github.com/swiftDialog/swiftDialog/wiki/Window-Size-and-Behaviour#--blurscreen
