### ISSUE TITLE
blurscreen not blurring the Space that SwiftDialog runs in

### ISSUE THREAD

**Issue by mikedowler** [swiftDialog/swiftDialog#255]
If an app is running in fullscreen (so that it has its own Space - aka virtual desktop) when SwiftDialog is triggered, then SwiftDialog obviously runs in a regular Space.  

However, if the `--blurscreen` option is used, then the only Space which gets blurred is the active Space, which is not necessarily the one where SwiftDialog is running.  E.g. if the fullscreen app was being displayed, then it is that Space which gets blurred.  When switching to the Space containing SwiftDialog, the background of that Space is not blurred.

Expected behaviour:
* At a minimum, the Space containing SwiftDialog should be blurred
* Ideally, _all_ Spaces should be blurred
* (Preferably, SwiftDialog opening should also switch the display to the Space in which SwiftDialog opens)

**Comment by bartreardon** [comment]
Are you able to give some steps or an example script that replicate the issue?

**Comment by mikedowler** [comment]
Sure!
1. Open a Terminal window in fullscreen mode
2. Run `dialog --blurscreen`
3. Observe that the Terminal window is blurred.
4. Use Mission Control to switch to the regular desktop Space where the SwiftDialog window is found.  Observe that the background to that window is NOT blurred.

Obviously, these conditions are slightly artificial, due to the need to trigger SwiftDialog locally.  But when we are pushing a SwiftDialog notification from MDM, it is very possible that the user might be working in a fullscreen app when SwiftDialog opens.  In that case, it is not at all obvious why their app has suddenly blurred - even if they switch back to the regular Space, there is nothing to associate SwiftDialog with the blurring of the fullscreen app, given that there is no blurring in the Space in which SwiftDialog is found.

**Comment by bartreardon** [comment]
I don't know if there's anything I can do about this in regards to positioning the dialog window on top of a fullscreen app in addition to a blurscreen due to how macOS manages full screen apps (as spaces but also not quite.

The blurscreen behaviour though should apply to all screens now though.
