### ISSUE TITLE
Fileselect: Intermittently, the file browser dialog sometimes comes up inactive and can't be used.  Workaround: click outside swiftDialog, then click back into swiftDialog.

### ISSUE THREAD

**Issue by bradtchapman** [swiftDialog/swiftDialog#279]
**Describe the bug**
Sometimes the file browser dialog opens in an inactive, unclickable state: the buttons are greyed out; files / folders cannot be selected; and keyboard navigation results in system alert sounds.  The only fix so far is to click another app outside swiftDialog (e.g.: Finder or the desktop) and then click the file browser again.  Subsequent invocations via the 'Select' button result in a usable file browser dialog.

I believe this condition is related to the intermittent issue where swiftDialog has no visible blinking cursor in text fields.  The reported issue with file picking only occurs when swiftDialog is in this state of focus.  This occurs on 25-50% of launches.  If swiftDialog does launch with a blinking cursor in text fields, then the file picker is fine.  Alternatively, an instance of swiftDialog with no visible cursor can be cured by clicking out then back in, and this will fix the file selector too.

**To Reproduce:**
A: Initialization of Test Scenario:
1. Create a swiftDialog form with at least two text fields, including one `editor`, and a text field with `fileselect`.
2. Launch SwiftDialog.
3. Click the first available text field.
4. Try typing any text into the box.
5. Note whether you see a blinking cursor, and follow the testing path below based on the result:

B: If you DO see a blinking cursor:
1. Click the [Select] button.
2. Does the file browser respond to mouse clicks? 
3. Try using [Tab] and arrow keys to navigate files in this view.
4. If the browser responds normally, note the result.
5. Relaunch SwiftDialog and repeat the Initialization steps (A:1-5) 

C: If you do NOT see a blinking cursor
1. Click the [Select] button.
2. Does the file browser respond to mouse clicks?
3. Try using the [Tab] and arrow keys to navigate files in this view.
4. If the browser DOES NOT respond to human input, click the [Cancel] button and repeat steps 1-3 to confirm the dialog remains unfocused and uncontrollable.
5. Click [Cancel] one more time.  
6. Now click **outside** the swiftDialog app, then click anywhere in the app again.
7. Repeat steps 1-3 above and note the result.

**Expected behavior**
I think a different unrelated condition affecting application focus is causing knock-on effects.  The file browser should be interactive and respond to human input all the time.  

**Screenshots**
See enclosed screen recordings.

**Desktop (please complete the following information):**
 - macOS version: 13.4.1
 - swiftDialog version: 2.2.1

**Comment by bradtchapman** [comment]
# Screen Recording

https://github.com/bartreardon/swiftDialog/assets/32527656/7f60cf4b-b39e-43eb-91b4-a7884bfb4a07

**Comment by BigMacAdmin** [comment]
I can ditto this user experience. Running the same script repeatedly will result in different behavior regarding focus and whether it is possible to click inside a text field. 

Clicking another app and then back to the dialog window generally resolve the problem, however, if the blur screen option is being used, it is not really possible to click on another app which can result in a seemingly broken state.

I believe I sent Bart some screen captures of this a while back via direct message on Slack, and I could’ve sworn I opened an issue, but it appears I failed.

**Comment by bartreardon** [comment]
Can I get some advice whether this behaviour is fixed in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0) ?

**Comment by bartreardon** [comment]
this should be fixed in 2.3.1, at least I'm no longer able to replicate it using that version.

Can re-open if there's a reliable way to make the issue return using `/usr/local/bin/dialog` (you can probably make it happen if calling the Dialog.app binary directly since it appears to be a user environment issue that should now be taken care of)
