### ISSUE TITLE
Strange apple fonts error

### ISSUE THREAD

**Issue by tslucas** [swiftDialog/swiftDialog#281]
**Describe the bug**
A strange apple fonts error

**To Reproduce**
Use the dialog command via an mdm (running as root)

example:
`/usr/local/bin/dialog --title "APA I.T." --message "Your system has been running for $UPTIME days without a reboot.\n\n Please reboot this device by the end of the day or it will blow up." --width 700 --height 250 --titlefont size=28 --messagefont size=22 --alignment left --icon "$icons_dir/apalogo.png" --overlayicon "$icons_dir/redalert.png" --button1text "Okay, will do."`
the error doesn't occur until this command is ran

**Expected behavior**
No errors.

**Screenshots**
<img width="254" alt="image" src="https://github.com/bartreardon/swiftDialog/assets/105375251/33593520-9e74-4ba7-b94d-e2535cc8b336">

**Desktop (please complete the following information):**
 - macOS version 12.4
 - swiftDialog version 2.2.1-4591

**Additional context**
Mosyle MDM
14" MacBook Pro M1 Pro

**Comment by tslucas** [comment]
Thank you.

**Comment by tslucas** [comment]
> This is a known Apple bug and not a bug with SwiftDialog. XType Font errors can be safely ignored.

Thank you.

**Comment by bartreardon** [comment]
closing as known/notissue
