### ISSUE TITLE
Change color of specific letters/pieces of text

### ISSUE THREAD

**Issue by tslucas** [swiftDialog/swiftDialog#283]
**Is your feature request related to a problem? Please describe.**
Id like to be able to change the font color of specific text/numbers in my message
**Describe the solution you'd like**
have the ability to make specific letters/pieces of text a different color for emphasizing 
**Describe alternatives you've considered**
Bolding the text...

**Comment by bartreardon** [comment]
Hi, sorry I won't be able to address this. The issue in implementing this and support markdown is too complex for this type of app.

There are options within markdown for emphasising text that can be used but as markdown does not directly support colours and the implementation in swiftDialog does not support using html tags.

**Comment by bartreardon** [comment]
closing this as a wontfix
