### ISSUE TITLE
Implement "actions" that take place when interacting with Notification Centre notifications

### ISSUE THREAD

**Issue by wegotoeleven** [swiftDialog/swiftDialog#285]
As per a brief discussion in MacAdmins Slack (https://macadmins.slack.com/archives/C01U5MXNGG6/p1689323590926389), this FR is to implement actions that can be triggered upon interacting with a swiftDialog Notification Centre banner or alert notification. 

This would replicate the same functionality in:
- [dataJar's Notifier](https://github.com/dataJAR/Notifier) (`--messageaction` and `--messagebuttonaction`)
- [IBM Notifier](https://github.com/IBM/mac-ibm-notifications) (`-main_button_cta_payload`, `-secondary_button_cta_payload` and `-tertiary_button_cta_payload`)

Most alerts/banners in the Notification Centre are interactive, i.e clicking on the notification would typically take you to an app or part of the OS that is referenced by said notification. For example, interacting with a native "Software Update" notification typically opens System Settings/Preferences, to the Software Update pane. It would be awesome if similar functionality could be added to swiftDialog's notification functionality.

**Comment by bartreardon** [comment]
Watch this space ;)

**Comment by PhillyPhoto** [comment]
Looking forward to this! I'm launching Dialog via LaunchDaemon so the window doesn't close when my policy in Jamf in complete. But since it could still be displaying after the script it done, there's no way to capture what the return code is to then perform a command. I would like to have button 1 restart the computer after the user reviews the information.

**Comment by bartreardon** [comment]
Addressed in v2.4  (latest release [2.4.1](https://github.com/swiftDialog/swiftDialog/releases/tag/v2.4.1) )
