### ISSUE TITLE
Button associated with a list item to trigger an action

### ISSUE THREAD

**Issue by FranckSartori** [swiftDialog/swiftDialog#287]
I'd like to be able to display a button associated with a list item to trigger an action when it's clicked.

This button needs to have a custom name, so that it can be different for each item in the list. It will probably be displayed before the icon. When a button is clicked, the list item must be written to a file (or something better) so that a loop can read the file and determine that a specific button has been clicked. swiftDialog does not need to execute any action, but only give a report of what was clicked.

I have no alternative for this scenario.

**Comment by bartreardon** [comment]
Hi - I don't see a use case for this that can't be served by checkboxes using a switch style, which can also display an app icon.

Performing actions within a running dialog based on user input in that same dialog is currently not something im working on but may look at in the future.

**Comment by FranckSartori** [comment]
Hi. In the first project requiring this function, a main dialog (pane) has an item list dynamically populated by external events (not linear workflow). And on a specific item list, you may choose to click on a "Details" button to display a dialog which is also going to have a dynamic list of items reporting what is happening on the list item clicked (linear workflow). The mechanism only knows to be informed that a "Details" button has been clicked to trigger the display of a new dialog. If technically feasible, I will be very happy to finally being able to give a chance to this project thanks to swiftDialog. DEPNotify was obviously limited to linear workflows whereas it appears it clearly appears that swiftDialog can break this boundary. So let's see what the future is going to be !

**Comment by bartreardon** [comment]
closing as wontfix (more accurately, not that it isn't a good idea, but I don't have any immediate plans to implement something like this since swiftDialog currently does not have any in-progress actions and adding that type of stuff isn't on the radar)
