### ISSUE TITLE
With v2.3 PDF files no longer work as banners or icons

### ISSUE THREAD

**Issue by robertryansqub** [swiftDialog/swiftDialog#295]
**Describe the bug**
In version 2.1 & 2.2 of SwiftDialog I used PDF files as banner and icon files for listitems. This does not work in 2.3 and there is instead a blue icon with a question mark. 

**To Reproduce**
Run SwiftDialog with a PDF file as header image or icon.

**Expected behavior**
The PDF should be displayed like any other image file, as happened in v2.2 and previous.

**Desktop (please complete the following information):**
 - macOS 14.0
 - swiftDialog 2.3

**Comment by bartreardon** [comment]
fixed in v2.3.1
