### ISSUE TITLE
Vector Icon Support (SVG, PDF) Broken in Version 2.3.0.4704 or Higher

### ISSUE THREAD

**Issue by kennyb-222** [swiftDialog/swiftDialog#296]
**Describe the bug**
SVG and PDF (and perhaps other) image types are no longer supported in version "2.3.0.4704" or higher of swiftDialog, causing the icons to be displayed as question marks. This affects the quality of image reproduction and impacts the usability of vector-based attributes.

**To Reproduce**
1. Download/Install 'swiftDialog version 2.3.0.4704 or higher'
2. Execute the following command:
`dialog --icon 'https://www.apple.com/ac/globalnav/2.0/en_US/images/ac-globalnav/globalnav/apple/image_large.svg'`
4. See the question mark icon instead of the expected SVG image

**Screenshots**
`2.2.1-4591` Screenshot:
<img width="932" alt="Screenshot 2023-08-15 at 10 25 45 AM" src="https://github.com/bartreardon/swiftDialog/assets/63611879/93f843fd-d617-4f1c-9244-26ff6780256f">
`2.3.0.4704` Screenshot:
<img width="932" alt="Screenshot 2023-08-15 at 10 26 41 AM" src="https://github.com/bartreardon/swiftDialog/assets/63611879/a136062c-3268-461d-bc64-02d08c8abb94">

**Expected behavior**
SVG and PDF icons should be displayed correctly, retaining the vector-based attributes and ensuring high-quality image reproduction.

**Desktop (please complete the following information):**
 - macOS version: 13.5
 - swiftDialog version: 2.3.0.4704 or higher

**Additional context**
This issue started occurring with the update to version "2.3.0.4704" or higher.

**Comment by kennyb-222** [comment]
`2.2.1-4591` Screenshot:
<img width="932" alt="Screenshot 2023-08-15 at 10 25 45 AM" src="https://github.com/bartreardon/swiftDialog/assets/63611879/93f843fd-d617-4f1c-9244-26ff6780256f">
`2.3.0.4704` Screenshot:
<img width="932" alt="Screenshot 2023-08-15 at 10 26 41 AM" src="https://github.com/bartreardon/swiftDialog/assets/63611879/a136062c-3268-461d-bc64-02d08c8abb94">

**Comment by bartreardon** [comment]
build 4704 was released back in June. Any reason why reporting this issue was withheld until after final release?

**Comment by bartreardon** [comment]
in the release notes:

> Processing of images (local, http) is now performed asynchronously which should result in better performance now that we aren't waiting on image resources on the main thread

Is likely the result as I switched from a raw "get file" to using AsyncImage which apparently doesn't support SVG or PDF. 

I'll look at this for the next release but this is the reason why I was pushing out those validation releases to get feedback on these changes. I can't hit every use case and since I personally don't use SVG's or PDF's this didn't get raised by my tests (or by anyone else that I knew was running the betas)

**Comment by kennyb-222** [comment]
Hi @bartreardon,

Thank you for the "swift" response and the clarification on the changes made in build `4704`. I must admit, it's my fault for not keeping up-to-date with the swiftDialog pre-release versions and validation releases. I appreciate your explanation about the switch to AsyncImage, and I understand that it may have led to the issue with SVG and PDF support.

I realize the importance of community feedback during the development process, especially for use cases that may not be part of standard testing. I'll make an effort to engage more actively with future validation releases to help identify any potential issues.

I'm glad to hear that you'll look into this for the next release. The support for SVG and PDF formats is valuable for my use case, and I appreciate your willingness to address it.

Thank you again for your dedication to swiftDialog, and please let me know if there's anything else I can do to assist.

Best,
Kenny

**Comment by bartreardon** [comment]
All good - so far svg/pdf support is the only major "bug" in 2.3 that's been raised so I consider it an overall win.

Doing some research AsyncImage is pure image and SVG's aren't images in the sense that AsyncImage thinks of them (i.e. bitmaps). There are some ideas though for extending support and piping SVG and PDF through the standard image processing but I'll have to experiment a little.

**Comment by bartreardon** [comment]
Fixed in 2.3.1
