### ISSUE TITLE
centreicon + image results in duplicate icon below image

### ISSUE THREAD

**Issue by WardsParadox** [swiftDialog/swiftDialog#302]
**Describe the bug**
If calling swiftDialog with a `--image` and `--centericon` (with it's required `--icon`), swiftDialog will display the icon twice, once above and once below the image.

**To Reproduce**
1. Specify an icon
2. Specify an image
3. Run dialog with either `jsonstring` or specify the cli options
4. See screenshots

**Expected behavior**
One icon should be displayed

**Screenshots**

| Centericon + image | No Centericon |
|--------|--------|
| <img width="350" src="https://github.com/swiftDialog/swiftDialog/assets/8117192/110b6453-5a09-482a-a6c9-e7710a528bdc " /> | <img width="350" src="https://github.com/swiftDialog/swiftDialog/assets/8117192/f671229d-0e17-45a7-8ab4-e33bb8e630da" />  | 

**Desktop (please complete the following information):**
 - macOS version, 14.0
 - swiftDialog version, 2.3.2.4726

Example command to replicate:
```sh
dialog --jsonstring '{"big": true, "blurscreen": true, "button1text": "I understand the risks!", "centericon": true, "height": "60%", "icon": "https://d1j6m02t14jk77.cloudfront.net/assets/macOS_Sonoma.png", "iconsize": 160, "infobutton": true, "infobuttonaction": "wikilink", "infobuttontext": "macOS Sonoma Wiki", "image": "https://d1j6m02t14jk77.cloudfront.net/assets/AEE2AE73-E36B-439A-8859-E2F90928424A/future.gif", "message": "/var/tmp/messager/AEE2AE73-E36B-439A-8859-E2F90928424A.md", "messagealignment": "left", "messagefont": "font=Amazon Ember", "moveable": false, "quitoninfo": true, "title": "Welcome to macOS Sonoma!", "titlefont": "color=#FF9901,font=Amazon Ember"}'
```

**Comment by bartreardon** [comment]
Closing this as it was fixed in an earlier release
