### ISSUE TITLE
FR: Ability to specify a solid color for the banner image in addition to using an image.

### ISSUE THREAD

**Issue by mm2270** [swiftDialog/swiftDialog#303]
**Is your feature request related to a problem? Please describe.**
_I'm not sure if something like this is possible, but it would nice if it's feasible to include in a future version._

Since we have the ability to use banner text that displays above a banner image, it would be nice to also be able to specify a solid color (or gradient - see below) for the banner instead of just an image. If I want to have a solid color banner and custom text above it, I have to deploy an image with the right specifications to use it as a banner.

**Describe the solution you'd like**
I'd like the ability to use something like `--bannerimage "color=#0349fc"`, or `--bannerimage "color=blue"` which would fill the banner area with a solid color, then I can use something like `--bannertitle "Welcome to your Mac" --titlefont "color=white,shadow=1` to display text above the banner.

It would be an awesome bonus if we could also specify some kind of gradient as well, like `--bannerimage "color1=#0349fc, color2=#6f8ad1"`

**Describe alternatives you've considered**
I currently deploy images in my scripts by base64 encoding them into the script and then generating the images in place by base64 decrypting them to a location on disk and using them. So I can achieve the above with this method, but it still involves making some kind of image for the banner, which is nothing but a solid background color, base64 encoding it, etc, etc. It's a little bit of extra work every time, and if I choose to later change the color, I have to repeat the process.
I've found that for this purpose, I can use a very tiny image of only 1x1 or 2x2 pixels, and swiftDialog will scale the image to fill the space as designed. So it doesn't need to a large image. It does still involve deploying it to the endpoints in some way though.

**Additional context**
No screenshots to show as I think it's pretty self explanatory.

If something like this can't be done, or you don't feel it's worth the effort, I would certainly understand. It does feel a bit niche in usefulness, but I think it would be a nice addition to the product nonetheless.

**Comment by bartreardon** [comment]
I like it.

I have some code that already does this (did, at least) when presenting an error image for banners, I'd just need to expose it as a configurable option.

**Comment by mm2270** [comment]
Hi @bartreardon, just wanted to check on this to see if there was a thought or plan for when this might get implemented. Might it be coming in a near future update? Was just wondering. No major rush, thanks!

**Comment by bartreardon** [comment]
I'm currently working on 2.3.4 (which might end up as 2.4.0) but not planning a release until next year. This request is on the list of things to look at implementing.

**Comment by bartreardon** [comment]
will be implemented in v2.4.0

`dialog --bannerimage colour=blue`

<img width="727" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/3598965/fda26a47-b273-4531-b4f1-446af3f30e34">

also can accept hex `--bannerimage colour=#0000ff`

**Comment by bartreardon** [comment]
Addressed in 2.4 (latest release [2.4.1](https://github.com/swiftDialog/swiftDialog/releases) )
