### ISSUE TITLE
SwiftDialog window doesn't show up in fullscreen mode

### ISSUE THREAD

**Issue by noahtalerman** [swiftDialog/swiftDialog#304]
**Describe the bug**

When the end user is using an application in fullscreen mode and SwiftDialog triggers the window to popup with `--blurscreen`, the window doesn't appear. The application in fullscreen mode is blurred.

If the user exits full screen mode, the window still doesn't appear.

Note that I'm not sure if this bug occurs if `--blurscreen` isn't used.

**To Reproduce**
1. Open any application in fullscreen mode
2. Trigger SwiftDialog with `--blurscreen`

**Expected behavior**

When the end user is using an application in fullscreen mode and SwiftDialog triggers the window to popup with `--blurscreen`, the window appears.

I think existing the fullscreen app and showing the window or showing the window over the full screen app are acceptable solutions.

**Desktop (please complete the following information):**
 - macOS version: `13.5.1`
 - swiftDialog version: `2.1.0-4148`

**Additional context**

We're currently using SwiftDialog to encourage the end user to migrate from their old MDM solution. We've seen some end users run report that they can't find the modal when they're working in fullscreen mode.

**Comment by kennyb-222** [comment]
I'm wondering if SwiftDialog could check if there's already an active application running in fullscreen mode when triggered. If so, SwiftDialog might also toggle into fullscreen mode using [toggleFullScreen(_:)](https://developer.apple.com/documentation/appkit/nswindow/1419527-togglefullscreen) to ensure its window appears on top, working around the bug.

**Comment by cvsmith122** [comment]
Bartreardon did say via slack - "there's a property on the window that allows it to be visible on all spaces/screens. it should also display over fullscreen apps if set correctly" It would be great if we could add this to swiftdialog as i have a bunch of students who get a --ontop with --blurscreen but dont know how to swipe to another window, and its causing extra support tickets and walk up traffic to the support office.
