### ISSUE TITLE
SF Symbol Icon Does Not Render in Multicolour Mode with `auto` Colour Value

### ISSUE THREAD

**Issue by macserv** [swiftDialog/swiftDialog#306]
**Describe the bug**
There exists a discrepancy between the documentation, and the actual handling of multicolour SF Symbols when the colour value auto is specified. Currently, this value does not actually allow the Symbol to be displayed in multicolour mode, as its `.symbolRenderingMode` is set to `.hierarchical`. This is fixed by adding a `var` to track the usage of `auto`, and a check against that `var` to determine whether `.hierarchical` or `.multicolor` symbol rendering should be used.

**To Reproduce**
1. Run the following command: `dialog --icon 'SF=airplane.circle.fill,colour=auto'`
2. Observe that the icon is rendered in hierarchical mode (grayscale, since the `.primary` colour is being applied by default).

**Expected Behaviour**
The icon should be rendered in multicolour mode (with an orange appearance, as shown in the documentation).

**Desktop (please complete the following information):**
 - macOS 14.0 23A344
 - swiftDialog @2.3.2

**Additional context**
Opened pull request #305 which includes a fix for this issue.

**Comment by bartreardon** [comment]
fixed in 2.4 (latest release [2.4.1](https://github.com/swiftDialog/swiftDialog/releases) )
