### ISSUE TITLE
Additional blank window in fullscreen mode

### ISSUE THREAD

**Issue by karanzazu** [swiftDialog/swiftDialog#308]
I am seeing an additional blank window appearing over top of Dialog when in fullscreen mode. It doesn’t appear in any other mode and not even when using `--blurscreen.` It’s only when using `--fullscreen`. I’ve been able to replicate this issue on a few Macs, all running Dialog v2.3.2.4726 and either macOS 13.5.2 or macOS 14.0.  If I downgrade Dialog to v2.1.0.4148, I no longer have the issue.

The function I'm using is below

`InstallInProgressMessage() {
IN_PROGRESS_TITLE="MY TITLE"
IN_PROGRESS_MESSAGE="This is my message"

"${SWIFT_DIALOG}" -p -d -o \
--icon "${ICON}" \
--title "${IN_PROGRESS_TITLE}" \
--titlefont "color=red,size=20" \
--message "${IN_PROGRESS_MESSAGE}" \
--messagefont "size=14" \
--centericon \
--quitkey "J" \
--button1disabled \
--fullscreen

/bin/echo "${?}"
}`

<img width="855" alt="NotifyFSIssue" src="https://github.com/swiftDialog/swiftDialog/assets/14316484/97bdff73-6ddf-4558-a153-7d5cc26944d0">

**Comment by BigMacAdmin** [comment]
I sent you here to github to make an issue, but on second look I see you're using -p (--ontop) along with Full Screen mode. This is redundant and unnecessary, and it appears that omitting that option prevents the bug.

Still a bug, but avoidable by using the proper flags. Fullscreen already implies "on top".

**Comment by bartreardon** [comment]
correct - the fullscreen representation is actually a seperate fullscreen window that appears over the actual dialog window

It's a bug but only in the sense that the z order of the windows is not enforced. As @BigMacAdmin suggests, don't use the `-p` option as it's not required.
