### ISSUE TITLE
FR: Option to enable button 1 after a delay

### ISSUE THREAD

**Issue by phillymjs** [swiftDialog/swiftDialog#309]
Would it be possible to add an option like "--button1delay [seconds]" so button 1 is disabled at first and displays a countdown of a specified number of seconds on the button, and then enables the button with the specified text?

e.g. **--button1text "Defer" --button1delay 10** would give a 10 second countdown and then enable the button and replace the text with "Defer"

![enabledelay](https://github.com/swiftDialog/swiftDialog/assets/5480797/37d0acd4-cc45-4322-ad3c-5ea6637507d8)

This behavior is achievable currently by backgrounding the dialog process and sending stuff to the command file, but it would be great if it could be a built-in feature.

**Comment by bartreardon** [comment]
you don't have to background the dialog, just the process managing the update.

You can do this as a one liner e.g. 
`$(for i in {10..0}; do echo "button1text: $i" >> /var/tmp/dialog.log; sleep 1; done; echo "button1text: Defer" >> /var/tmp/dialog.log; echo "button1: enabled" >> /var/tmp/dialog.log) & dialog --button1text 10 --button1disabled --button2text "Open Software Update"`

or as the following in a script:

```bash
function deferCountdown() {
    for i in {10..0}; do
        echo "button1text: $i" >> /var/tmp/dialog.log
        sleep 1
    done
    echo "button1text: Defer" >> /var/tmp/dialog.log
    echo "button1: enabled" >> /var/tmp/dialog.log
}

deferCountdown & dialog --button1text 10 --button1disabled --button2text "Open Software Update"
```

**Comment by bartreardon** [comment]
given there are other ways to achieve this I'm closing this as wontfix
