### ISSUE TITLE
FR: Allow Checkboxes to be moved to the Right of the Labels

### ISSUE THREAD

**Issue by mike-wolf23** [swiftDialog/swiftDialog#313]
**Is your feature request related to a problem? Please describe.**
While it is not a probelm it would be great if the UI supported the ability to change the side the Checkboxes were on from the compared to the text

**Describe the solution you'd like**
The Checkboxes with the --checkbox flag appear on the Left hand side.  Adding a flag to move them to the right would be a nce UI enhancement.

**Describe alternatives you've considered**
The --checkboxstyle switch flag moves the switches to the right, but the switch UI element is a little too "new school" for what my application is.

**Comment by bartreardon** [comment]
Not something I'd implement.

the [HIG for checkboxes](https://developer.apple.com/design/human-interface-guidelines/toggles#Checkboxes) as well as the [developer documentation](https://developer.apple.com/documentation/swiftui/togglestyle/checkbox) and general convention place the checkbox in front of the label. 

Indeed, `Toggle("Label Name").toggleStyle(.checkbox)` always renders the checkbox first
