### ISSUE TITLE
Make --button1disabled change based on state of checkbox on the same dialog

### ISSUE THREAD

**Issue by pukoc** [swiftDialog/swiftDialog#314]
Hi, regarding --button1disabled, I want to use it in a way where on launch button 1 is disabled but then i have a checkbox i want the user to check on the same page, if that is checked dynamically enable it again so they can proceed.

Cheers,
Eugen

**Comment by bartreardon** [comment]
Something like this?

<img width="727" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/3598965/94970d84-71ee-4cf4-839b-032d63409234">

<img width="727" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/3598965/bde9212c-de4e-43af-97e0-32b16add32ea">
