### ISSUE TITLE
When using notifications on macOS Sonoma, if the displayed text exceeds the standard notification format limit, the collapse button does not appear.

### ISSUE THREAD

**Issue by qudly** [swiftDialog/swiftDialog#315]
**Describe the bug**
When given text is too long for the default notification display, a collapsible button does not appear.

**To Reproduce**
1. Runing this command to show a notification :
`/usr/local/bin/dialog --notification --title "Your Mac need a reboot" --message "Est adipiscing consectetur elit ullamco occaecat elit aute sit laborum. \nMagna laboris sint aliquip tempor nisi irure irure aliquip voluptate magna aliquip aute laborum aute. Ex id veniam sit proident tempor enim laboris dolore ea mollit elit fugiat et fugiat laborum lorem eiusmod."`
2. Notification appear without collapse button

**Expected behavior**
I assume that a behavior similar to macOS Ventura would be desirable, where we can see the button to expand the notification to read the complete text.

**Screenshots**
<img width="376" alt="Screenshot 2023-10-06 at 14 58 14" src="https://github.com/swiftDialog/swiftDialog/assets/32485368/e06aba4c-246e-4bd8-9c3d-6d3481eff710">

**Desktop:**
 - macOS Sonoma 14.0
 - swiftDialog version 2.3.2

**Additional context**
The behavior on macOS Ventura remains unchanged, the issue seems to be present only on macOS Sonoma.

**Comment by bartreardon** [comment]
this appears to be a change in how notifications are processed in Sonoma. Advice at this stage would be to limit what is displayed in a notification to content that can be communicated without requiring the user to expand the text.

I'll be working on some notification tweaks though so I'll see if there's an option for this or not.
