### ISSUE TITLE
Infobox not supporting single <br> when updating via /var/tmp/dialog.log

### ISSUE THREAD

**Issue by Tribruin** [swiftDialog/swiftDialog#316]
**Describe the bug**
Updating the infobox by sending a command to /var/tmp/dialog.log with single <br> in the text ignores the <br> and places the text on a single line. Inserting two consecutive <br>'s works, but adds an extra line between text

**To Reproduce**

1. Create a dialog box from the command line with an infobox:
` dialog --infobox "**MacBook Air**<br>1234566<br>macOS10.6" --moveable &`
The text should add the proper cr/lf after Air and the number

2. Update the existing dialog box by adding to the dialog log:
`echo "infobox: **MacBook Air**<br>1234566<br>macOS10.6" >> /var/tmp/dialog.log`
The number will be on the same line as the computer description

This behavior happens both when replacing the existing infobox or adding to the infobox (+)

**Expected behavior**
A single <br> should add a cr/lf, like is does from the command line. 

**Screenshots**
From Command Line
<img width="932" alt="Screenshot 2023-10-10 at 10 47 10 AM" src="https://github.com/swiftDialog/swiftDialog/assets/39201800/45e70274-a2f4-46e5-8fe8-df3c82d0f10c">

From /var/dialog/log
<img width="888" alt="Screenshot 2023-10-10 at 10 47 26 AM" src="https://github.com/swiftDialog/swiftDialog/assets/39201800/c6b75865-a39f-4d81-8ff3-2c1575b4bf31">

**Desktop (please complete the following information):**
 - macOS version - 13.6
 - swiftDialog version - 2.3.2.4726

**Comment by bartreardon** [comment]
Correct. That's just how markdown works though. To insert a new line you want '[space][space]<br>' or you can (as you've discovered) insert a line break with '<br><br>'

'<br>' is just a alternate way of inserting '\n', the behaviour is the same.

**Comment by bartreardon** [comment]
This should be fixed in the next release. I've added general support for `<br>` wherever text is used.

**Comment by bartreardon** [comment]
Fixed in v2.5.0
