### ISSUE TITLE
Pull DDM Deadline

### ISSUE THREAD

**Issue by mat-griffin** [swiftDialog/swiftDialog#319]
With Sonoma and DDM updates now having a forced deadline but still using Notification Centre is it possible to add functionality in SD pull the update deadline and offer some formatting date/time formatting
Location is 
`var/db/softwareupdate/SoftwareUpdateDDMStatePersistence.plist`

```
	"TargetBuildVersion" => "23B74"
		"TargetLocalDateTime" => "2023-11-08T17:00:00"
		"TargetOSVersion" => "14.1"
}
```

Currently this can be added as part of the text in the dialog window

**Comment by bartreardon** [comment]
What @acodega said. SwiftDialog by itself doesn't do or know about anything. It just acts as a UI to whatever script you are using. 

If you have a script that requires that information then swiftDialog can certainly display it but that's up to the script to work out what to display and how.
