### ISSUE TITLE
Allow specifying the initial timer (not a new timer) via json 

### ISSUE THREAD

**Issue by WardsParadox** [swiftDialog/swiftDialog#322]
**Is your feature request related to a problem? Please describe.**
Currently Dialog does not support `timer` via JSON file or `jsonstring` initialization.

**Describe the solution you'd like**
Start a new dialog using json like so:
```json
{
	"title": "test",
	"timer": 30
}
```

**Describe alternatives you've considered**
ATM a workaround is to just insert a `--timer VALUE` into the command ahead of time based on the properties sent.

**Additional context**
N/A

**Comment by WardsParadox** [comment]
Well turns out this totally works....IF you string the timer.


Not Working:
```json
{
	"title": "test",
	"timer": 30
}
```
Working:
```json

**Comment by bartreardon** [comment]
For `v2.3.4` I've refactored how json/command line arguments are ingested. Apart from cleaning up the code, number values in json are properly processed as numbers. So `{"timer" : 30}` is now valid. The previous `{"timer" : "30"}` is also valid for backward compatibility.
