### ISSUE TITLE
FR: Add "computer" option for icon that displays an icon representation of the current device

### ISSUE THREAD

**Issue by bartreardon** [swiftDialog/swiftDialog#323]
slack thread https://macadmins.slack.com/archives/C19MR7EM9/p1701299047912239

code:

```swift
if messageUserImagePath == "computer" {
    Image(nsImage: NSImage(named: NSImage.computerName) ?? NSImage())
        .resizable()
}
```

**Comment by mm2270** [comment]
I like the additions being added into the 2.4.0 release, thank you!

I was playing around with the new "computer" option for icon, and I'm seeing a very fuzzy, low quality rendering for my Mac, which is a 2021 M1 MacBook Pro. Not sure why that would be.
Where and how does swiftDialog pull the icon from? If I view my Mac in the About This Mac window, under Displays, it shows a large high quality image for the device. Not really sure if that's what it should be pulling, but if so, it's scaling it down considerably and making it look terrible. Any ideas why that would be?

Adding a screenshot to show what I mean. The code used was simply `dialog --icon computer`

<img width="932" alt="Screen Shot 2024-01-02 at 4 53 22 PM" src="https://github.com/swiftDialog/swiftDialog/assets/3653600/e3bf5453-7492-4506-a528-a4cdeb34ff8d">

**Comment by bartreardon** [comment]
interesting.

The image is literally what I posted above: `Image(nsImage: NSImage(named: NSImage.computerName)`

`computerName` is a built in descriptor that returns the computer image. I've no idea where it actually gets it from. I can see if specifying an image size helps.

**Comment by mm2270** [comment]
OK, thanks. I did see that code, but not being a programmer, it didn't mean a lot to me when I looked at it.

I'm going to run this test script on a few other machines I have access to, to see if a) I can reproduce it, and it not, b) I can maybe narrow down what may be causing this. It is strange though.

**Comment by bartreardon** [comment]
are you running your display in native res or scaled (i.e. retina)?
