### ISSUE TITLE
Add swiftDialog into Homebrew?

### ISSUE THREAD

**Issue by mattpackwood** [swiftDialog/swiftDialog#327]
What do you think about making swiftDialog available via Homebrew as a cask?

It would make version updates easier and make you "easier to find" boost your visibility

**Comment by homebysix** [comment]
Given that swiftDialog is something typically managed by organizational administrators and not individual end users, I'm curious how this would make version updates easier. Homebrew is notoriously difficult to manage with scripts that run in root context, as most MDMs do.

**Comment by mattpackwood** [comment]
Fair enough!  I was just curious, I have seen a lot of software being added to Homebrew so I was curious.

**Comment by bartreardon** [comment]
pkg for swiftdialog is now in homebrew

`brew update && brew install --cask swiftdialog`
