### ISSUE TITLE
SF Symbols too small in 2.4.0.4746 (Beta 2)

### ISSUE THREAD

**Issue by Tribruin** [swiftDialog/swiftDialog#330]
**Describe the bug**
SF Symbols as icons in a list view are small not the same size as other icons. This is a change from Beta 1. 

**To Reproduce**
Create a list view with icons. 
Use a SF Symbol as the Icon (e.g. SF=lock.shield,color=#E30613,weight=regular)

**Expected behavior**
SF Symbols should be a similar size as other icons

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version 14.2.1
 - swiftDialog version 2.4.0.4746 (Beta 2)

**Comment by bartreardon** [comment]
this should be fixed in the latest beta https://github.com/swiftDialog/swiftDialog/releases/tag/v2.0.4.4747
