### ISSUE TITLE
Add message to listitem

### ISSUE THREAD

**Issue by martinvandiemen** [swiftDialog/swiftDialog#331]
**Is your feature request related to a problem? Please describe.**
I would like to add a description to the list item.

**Describe the solution you'd like**
Please description/text/body/message to listitem so that will appear below the title.

**Describe alternatives you've considered**
Currently I'm using the progresstext but this is only shown when the item is "active".

**Additional context**
Here is a mockup.
![message](https://github.com/swiftDialog/swiftDialog/assets/946622/6922839a-4c79-4870-950a-a4f24d9a3bea)

**Comment by mm2270** [comment]
Nice idea, if it's feasible to do. It would add some additional value in using swiftDialog for onboarding, although even in its current state, it's really good for those workflows. Anyway, I like it.

ATM, I use the main message text area for displaying information about the current install, but this seems like a nice improvement.

**Comment by bartreardon** [comment]
something like this?

<img width="932" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/3598965/865a8690-ec5b-4ac4-ad08-5a97f1c93aca">

**Comment by bartreardon** [comment]
available in the latest beta https://github.com/swiftDialog/swiftDialog/releases/tag/v2.0.4.4747

usage:
`--listitem "Item Title",subtitle="This is a subtitle"`

<img width="610" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/3598965/9435ba0d-08ab-4029-bfa8-60623fd451b3">

**Comment by dan-snelson** [comment]
Noice, Bart!

![Screenshot 2024-01-21 at 8 22 01 AM](https://github.com/swiftDialog/swiftDialog/assets/24623109/e2ad2d49-430e-4cc5-802c-1fc88cdd7829)

Looks like the commas which work fine in `progresstext` don't work so well in `subtitle`.

(I think I prefer that `subtitle` not intrude on the area used by `status`, but how do *you* know how much room _I_ want for `status` ? [Probably best to add a dedicate field for `subtitle` and encourage the admin to "keep it brief.")

**Comment by BigMacAdmin** [comment]
![Screenshot 2024-01-21 at 12 26 15 PM](https://github.com/swiftDialog/swiftDialog/assets/106293503/71e18fab-8e0c-4f9f-a8f4-be2120ca1452)
I think this looks great.

**Comment by martinvandiemen** [comment]
@bartreardon really great. I've tested this but the layout needs a bit more structure. Icon becomes quiet large, alignment looks off, the description is very small and hard to read. Could it maybe be more structured like my mockup? Thanks!

**Comment by martinvandiemen** [comment]
I noticed that a description with a comma in it results that the line breaks. Even when escaping the comma `\,` will still break the line.

**Comment by bartreardon** [comment]
If you are specifying the subtitle on the command line then the comma in your text will be interpreted as a separator. If you want more complex text then id recommend using json.

**Comment by bartreardon** [comment]
> @bartreardon really great. I've tested this but the layout needs a bit more structure. Icon becomes quiet large, alignment looks off, the description is very small and hard to read. Could it maybe be more structured like my mockup? Thanks!

Feel free to submit a PR with how you think it will look. I won't be able to do anything with it until the end of the month anyway
