### ISSUE TITLE
Allow individual --windowbuttons options

### ISSUE THREAD

**Issue by drtaru** [swiftDialog/swiftDialog#333]
The new `--windowbuttons` argument is great, however there are times when scripts would like to allow users to only minimize or fullscreen a window but not have the close button active, or some other combination.

A good solution for this would be to allow `--windowbuttons` to accept arguments. Have the default of nothing be all 3, but also allow an admin to pick and choose which of the three are actually active. Something like `--windowbuttons "close,minimize,fullscreen"` for all 3, or `--windowbuttons "minimize"` for only enabling the minimize button but disabling the close and fullscreen buttons, as an example.

This has been brought up a few times in various slack channels as a good idea since the initial beta was introduced, I'm just translating it into a full FR.

**Comment by drtaru** [comment]
I don't know swift but there was some discussion on whether or not this is feasible. I discovered where the code needs to go I just don't know enough to tie the options to the CLI arguments
Just need to add some lines in the main app and tie them to the args 
 ```
                    window?.standardWindowButton(.closeButton)?.isEnabled = false
                    window?.standardWindowButton(.miniaturizeButton)?.isEnabled = true
                    window?.standardWindowButton(.zoomButton)?.isEnabled = false
```
https://github.com/swiftDialog/swiftDialog/blob/dev_2.4.0/dialog/dialogApp.swift#L182-L184

**Comment by bartreardon** [comment]
available in the latest beta https://github.com/swiftDialog/swiftDialog/releases/tag/v2.0.4.4747 

usage:
`--windowbuttons close,max` 

will enable only the close and maximise button (`max` is disabled anyway unless you also use the new  `--resizable` argument)
