### ISSUE TITLE
Icon alignment issues in beta 2.4.0.4748 

### ISSUE THREAD

**Issue by BigMacAdmin** [swiftDialog/swiftDialog#334]
**Describe the bug**
Alignment is off for icons in SwiftDialog beta 2.4.0.4748

**To Reproduce**
`/usr/local/bin/dialog --listitem Terminal,icon=/System/Applications/Utilities/Terminal.app --listitem Thing,icon=SF=restart.circle`

**Expected behavior**
Icons are not aligned vertically with the rows. Icons are also smaller (both App icons and SF symbols) which may or may not have been intentional.

**Screenshots**
![2 4 0 4748](https://github.com/swiftDialog/swiftDialog/assets/106293503/ddcf5d75-e8ea-4e03-92c3-ea63899c164d)
![2 3 3 4734](https://github.com/swiftDialog/swiftDialog/assets/106293503/6c8e1d2c-575c-4ce7-bdb5-2ccd9bf1748f)

**Desktop (please complete the following information):**
 - macOS version 14.3
 - swiftDialog version 2.4.0.4748

**Comment by bartreardon** [comment]
SwiftUI is like CSS

IYKYK

**Comment by bartreardon** [comment]
<img width="450" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/3598965/bf40cfc3-d756-4884-8f01-f3ea50728a40">

**Comment by bartreardon** [comment]
Fixed in [2.4.1](https://github.com/swiftDialog/swiftDialog/releases/tag/v2.4.1)
