### ISSUE TITLE
default notification icon

### ISSUE THREAD

**Issue by mltsalg** [swiftDialog/swiftDialog#338]
**Describe the bug**
I've replaced the company default logo with mine (1024x1024 also 512x512) but it still shows a very tiny and old logo post attempts to change it a completely different logo of the same size. My log and script below.. Unsure if this is likely a bug? If not, how can I correct this?

**To Reproduce**
```
#!/bin/bash

png_file="/Users/Shared/Jamf.png" 
temp_file=$(/usr/bin/mktemp)
dialogDir="/Library/Application Support/Dialog"


/bin/cp "$png_file" "$temp_file"
sleep 2

sudo /bin/mkdir -p "$dialogDir"
sleep 2

sudo /usr/bin/sips -s format png "$temp_file" --out "$dialogDir"/Dialog.png
sleep 2
```

**Screenshots**
<img width="370" alt="smallNotifcationIcon" src="https://github.com/swiftDialog/swiftDialog/assets/135068922/b774b06c-489f-4272-a7ad-eba8aa9817e4">

**Desktop (please complete the following information):**
 - macOS version 13.6.4
 - swiftDialog v2.3.3

**Comment by dan-snelson** [comment]
@mltsalg:

On the off-chance the following proves helpful:

[A. Add the swiftDialog Pre-install script to your Jamf Pro server](https://snelson.us/2023/03/swiftdialog-notifications/#A)

**Comment by drtaru** [comment]
Your temp file variable won't work like that, you are calling mktmp but not telling it where to make the temp file...
But then why do you even need that? If you are supplying a png there's no need to cache it again.

```
#!/bin/bash

png_file="/Users/Shared/Jamf.png" 
dialogDir="/Library/Application Support/Dialog"

sudo /bin/mkdir -p "$dialogDir"
sleep 2

sudo /usr/bin/sips -s format png "$png_file" --out "$dialogDir"/Dialog.png
sleep 2
```

**Comment by mltsalg** [comment]
Hi @drtaru, -appreciate the feedback.
I've made the change in my script which works as intended


Hi @dan-snelson, -appreciate the feedback also
I've completed the required steps but can't seem to wrap my head around why the wrong notification icon is being displayed.
Any input is appreciated. Thank you

![Screenshot 2024-02-08 at 5 32 07 PM](https://github.com/swiftDialog/swiftDialog/assets/135068922/e2995709-30f4-40ef-b034-7d87544724e8)
![Screenshot 2024-02-08 at 5 32 02 PM](https://github.com/swiftDialog/swiftDialog/assets/135068922/9393c25e-4f6f-4f77-9c89-930e1fa291e3)

**Comment by drtaru** [comment]
Can you run the following and post the result?

`sudo killall NotificationCenter`
Wait like 5 seconds
`dialog --notification --title "Test Notification" --message "A test notification message"`

**Comment by mltsalg** [comment]
Wow! That seems to have done it. Now displays correctly. Many thanks again as I am on to further testing. 

![image](https://github.com/swiftDialog/swiftDialog/assets/135068922/5b92f1bb-10d4-4e54-b16e-c8d5481bbcd0)

**Comment by bartreardon** [comment]
Closing this as it appears to be resolved.
