### ISSUE TITLE
Cancel Action Button to Close Notifications

### ISSUE THREAD

**Issue by mar-jac** [swiftDialog/swiftDialog#339]
**Is your feature request related to a problem? Please describe.**
There isn't a direct cancel button to exit the notification. I know with both button arguments you can create custom actions for them. 

**Describe the solution you'd like**
A button_cancel argument that executes to cancel/exit/close the notification.

**Describe alternatives you've considered**
Said argument should have the system notification to exit out.

**Additional context**

**Comment by mar-jac** [comment]
Maybe make them alert style notifications.

**Comment by bartreardon** [comment]
That's not quite how notifications work.

You have control over the notification type so you can make it alert or banner style as you see fit, either manually or with a config profile.

v 2.4 has notification actions which can perform an action based on what options is selected. Clicking a notification or selection an action dismisses the notification. what happens after that depends if you have defined any actions to take.

**Comment by mar-jac** [comment]
I just realized that 2.4.0 is still in beta. I'm on 2.3.3

**Comment by bartreardon** [comment]
I just released 2.4 as the latest version (same build as RC 1)

there's no built in "make a noise" functionality. If you want to do that then you will need to play a sound or something as part of your script.

**Comment by mar-jac** [comment]
Sure thanm you. I wanted to confirm since i believe dialog is silent by default. Wanted to confirm it doesnt play sounds or if it did if there was a setting for it.

**Comment by bartreardon** [comment]
Not intentionally 🙂

**Comment by mar-jac** [comment]
No worries, would be good to have, especially for sending out important system notifications. On another note, is the `--notification` argument a boolean or a string?

**Comment by bartreardon** [comment]
`--notification` is a bool condition that causes swiftDialog to send message, title etc as a system notification instead of as a pop up dialog.
