### ISSUE TITLE
Documentation Correction - Notifications/Setting an action

### ISSUE THREAD

**Issue by BigMacAdmin** [swiftDialog/swiftDialog#340]
📝 📝 📝 
Correcting some typos for the new "Setting an action" section of the Notifications wiki page.
📝 📝 📝 

## Setting an action

In v2.4.0 or newer, you can set an action to be performed when the user clicks on the notification. This can be a URL or a script.

The most basic use for this feature is:

`--notification --title "<text>" --message "<text>" --button1action "open -a Safari.app"`

`--notification --title "<text>" --message "<text>" --button1action "https://swiftdialog.app/"`

You can specify an additional action and define the button labels :

`--notification --title "<text>" --message "<text>" --button1text "Do Something" --button1action "/do/something" --button2text "Do Something Else" --button2action "/do/something/else/"`

--button1action will remain the default action if either the notification or button1 is actioned. button2action will only trigger if button2 is actioned.

**Comment by bartreardon** [comment]
should look better now

**Comment by BigMacAdmin** [comment]
> sent you a link to join the "swiftDialog" org - should allow you to ~clean up my mess~ fix the odd typo if you find one 🙂

It is with great reluctance that I have agreed to this calling...

I love democracy... I love The Republic...

The power you give me, I will lay down when this crisis has abated!

**Comment by bartreardon** [comment]
with great power comes ~great responsibility~ added support overhead
