### ISSUE TITLE
Empty Variables Now Contain Default Message

### ISSUE THREAD

**Issue by garrettthorn** [swiftDialog/swiftDialog#341]
**Describe the bug**
When passing an empty variable to SwiftDialog, it now displays the default text "This contains important message content Please read".

**To Reproduce**
My script that reproduces this error-
```
#! /bin/bash
userIDError=""

userid_dialog=$(/usr/local/bin/dialog \
   --title "Asset Check Out $version" \
   --message "$userIDError" \
   --button1text "OK" \
   --json \
   --button2)
```

**Expected behavior**
In previous versions of SwiftDialog, an empty variable would simply display no text, as shown below.

**Screenshots**
swiftDialog version 2.3.3.4734
![Screenshot 2024-02-06 at 10 27 23 AM](https://github.com/swiftDialog/swiftDialog/assets/159169001/8fe9d08e-dd57-4812-acb1-1b35a7a300be)
swiftDialog version 2.4.0.4750
![Screenshot 2024-02-06 at 10 25 02 AM](https://github.com/swiftDialog/swiftDialog/assets/159169001/abb50368-1d8a-4e83-9c2b-26c7d47f308e)

**Desktop (please complete the following information):**
macOS version - 14.3
swiftDialog version - 2.4.0.4750

**Comment by bartreardon** [comment]
cheers. I'll take a look.

in the meantime as long as there's something not null in there it won't default to the boilerplate text, e.g. `--message "$userIDError "` (added space after the variable)
