### ISSUE TITLE
‘Bumpy’ window appear

### ISSUE THREAD

**Issue by Melvin-P-NL** [swiftDialog/swiftDialog#342]
**Is your feature request related to a problem? Please describe.**
Certainly not.

**Describe the solution you'd like**
I like how the window of DEPNotify appeared with a ‘bumpy’ effect. Would that be possible with swiftDialog?

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by bartreardon** [comment]
I've had a look but no plans to implement anything along these lines in the foreseeable future.
