### ISSUE TITLE
Listitems display issue in 2.4.0

### ISSUE THREAD

**Issue by drtaru** [swiftDialog/swiftDialog#345]
**Describe the bug**
In SwiftDialog 2.4.0 when setting a list of `listItems` excluding the new `subtitle` parameter from my list of items. the list is displayed in an expanded manner. This is a change from SwiftDialog 2.3.3.

**To Reproduce**
SwiftDialog 2.4.0
`/usr/local/bin/dialog --width 700 --height 500 --moveable --ontop --titlefont size=20 --messagefont size=14 --progress 5 --icon caution --infobox '' --title '' --progresstext ' ' --message '' --jsonstring '{"listitem" : [{"title" : "Item One", "icon" : "/path/to/image", "status" : "pending", "statustext" : "Pending"},{"title" : "Item Two", "icon" : "/path/to/image", "status" : "pending", "statustext" : "Pending"}]}' --button1text text --json`

![image](https://github.com/swiftDialog/swiftDialog/assets/1212524/77193789-faa6-4493-9c88-82c8f4ca032b)

SwiftDialog 2.4.0 with `"liststyle" : "compact"`
`/usr/local/bin/dialog --width 700 --height 500 --moveable --ontop --titlefont size=20 --messagefont size=14 --progress 5 --icon caution --infobox '' --title '' --progresstext ' ' --message '' --jsonstring '{"liststyle" : "compact","listitem" : [{"title" : "Item One", "icon" : "/path/to/image", "status" : "pending", "statustext" : "Pending"},{"title" : "Item Two", "icon" : "/path/to/image", "status" : "pending", "statustext" : "Pending"}]}' --button1text text --json`
![image](https://github.com/swiftDialog/swiftDialog/assets/1212524/214cf94b-ef72-464b-9603-df489bb95172)

SwiftDialog 2.3.3
`/usr/local/bin/dialog --width 700 --height 500 --moveable --ontop --titlefont size=20 --messagefont size=14 --progress 5 --icon caution --infobox '' --title '' --progresstext ' ' --message '' --jsonstring '{"listitem" : [{"title" : "Item One", "icon" : "/path/to/image", "status" : "pending", "statustext" : "Pending"},{"title" : "Item Two", "icon" : "/path/to/image", "status" : "pending", "statustext" : "Pending"}]}' --button1text text --json`
![image](https://github.com/swiftDialog/swiftDialog/assets/1212524/3d368511-6a89-4582-b788-4f78dfa070f5)

**Expected behavior**
While not the end of the world this is a change from previous behavior, even when using `"liststyle" : "compact"` the behavior is not quite the same and I didn't see the mention of `liststyle` in the changelogs.

**Comment by bartreardon** [comment]
the latest beta of 2.4.1 should resolve this https://github.com/swiftDialog/swiftDialog/releases/tag/v2.4.1.4752
