### ISSUE TITLE
Allowing Button1Text with Button1Action on Notifications

### ISSUE THREAD

**Issue by mar-jac** [swiftDialog/swiftDialog#346]
**Is your feature request related to a problem? Please describe.**

As for now with 2.4.0, using `--button1action` allows to do any action just by clicking on the notification. Now, I think for other use cases I can see the benefit of seeing the `--button1text` on `--button1action` even if its the only button on the notification. 

**Describe the solution you'd like**

If possible, we can add `--button1text` to `--button1action`, even if its the only action. I think it would help people if they also saw where to click exactly cause they may close on it by accident.  This is for situations where the action is mandatory and there is one option.

An example:
![423105512_891736259399464_4120874393176829537_n](https://github.com/swiftDialog/swiftDialog/assets/55053226/3c26a7d1-a760-433c-ac5c-094bf1210052)

**Describe alternatives you've considered**

There may be a script but thought it would be easier if it was built in.

**Additional context**

**Comment by bartreardon** [comment]
the updated build here should do this
https://github.com/swiftDialog/swiftDialog/releases/tag/v2.4.1.4752
