### ISSUE TITLE
Cannot assign SF Symbol Color to list item icons using command line

### ISSUE THREAD

**Issue by BigMacAdmin** [swiftDialog/swiftDialog#348]
**Describe the bug**
`/usr/local/bin/dialog --listitem Thing1,icon=SF=person.fill` works as expected
`/usr/local/bin/dialog --listitem Thing1,icon=SF=person.fill,color=red` does not

There does not appear to be a way to use SF Symbol color via command line arguments.

In addition, the wiki does not document the ability to add list item icons via command line.

**To Reproduce**
1. Open a terminal and run the commands listed above.
**Expected behavior**
Same as when using a JSON file.

**Screenshots**
![image](https://github.com/swiftDialog/swiftDialog/assets/106293503/4ac570eb-42fd-447e-9753-8cfae25f0dda)

**Desktop (please complete the following information):**
 - macOS version 14.3
 - swiftDialog version 2.4.1.4753

**Additional context**

**Comment by bartreardon** [comment]
yeah, that's a tough nut to crack. The issue is that the options for a single argument are comma separated but `color=red` is a property of `icon` not of `listitem` and nested csv's don't nest. There is a precedent of sorts with how palette colours are specified for SF symbols but the code behind that is not what I would call pretty or easy to grok.

**Comment by BigMacAdmin** [comment]
I figured as much.

Should I make a note of this in the wiki, and close this out?

Something along the lines of:

List item icons can be set using the command line argument: `--listitem "<text>,icon=<image>"` however some more advanced features (like using SF Symbols with custom colors) are only supported when using JSON.

**Comment by bartreardon** [comment]
It's along the lines of "if you want more advanced control, you should use json" but not quite in those words

**Comment by BigMacAdmin** [comment]
https://github.com/swiftDialog/swiftDialog/wiki/Item-Lists#1-command-line

Updated this section.
