### ISSUE TITLE
Timer function stops working when buttonstyle option is used

### ISSUE THREAD

**Issue by K1jaff** [swiftDialog/swiftDialog#350]
**Describe the bug**
When using the command line option --timer in conjunction with the --buttonstyle option the timer no longer closes the window after the allotted time specified.

**To Reproduce**
Run the following sample command line in terminal to reproduce the error:  /usr/local/bin/dialog  --timer 10 --buttonstyle center  

**Expected behavior**
The dialog process should stop after 10 seconds and return exit code 4

**Desktop (please complete the following information):**
 - macOS version 14.3.1
 - swiftDialog version 2.4.1.4754

**Comment by bartreardon** [comment]
correct. as per the help text on `--buttonstyle`

```
--buttonstyle center|centre

	Configure how the button area is displayed

        Displays the buttons centered at the bottom of the window

        When using this mode, --timer and --infobutton are not available
```

**Comment by K1jaff** [comment]
D’oh so an RTFM issue. Ty dude.
