### ISSUE TITLE
Dialog windows quit Unexpectedly in 2.4.1

### ISSUE THREAD

**Issue by jeden-92** [swiftDialog/swiftDialog#351]
**Describe the bug**
Since updating to 2.4.1 my script which launches a dialog and then updates it with the update dialog command, will show the first dialog then the script progresses and the dialog will quit but the script still completes in the background. gives this error in the cmd output /usr/local/bin/dialog: line 18: 2296 Trace/BPT trap: 5    launchctl asuser "$uid" sudo -u "$currentUser" "$@"

**To Reproduce**
my script is a clone of this script https://github.com/PezzaD84/Assemble so running the unedited version will reproduce the issue, if run with an older version of dialog the script performs as expected. this occurs on ventura and sonoma.

**Expected behavior**
the dialog should not quit 

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version 13.6.4 and 14.3.1
 - swiftDialog version 2.4.1

**Additional context**

**Comment by BigMacAdmin** [comment]
I dug through this and can confirm this bug.

Easy to reproduce:
```
#!/bin/bash

/usr/local/bin/dialog -t "test" -m "message" & 

sleep 1

echo 'height: 200' >> /var/tmp/dialog.log
```

Sending a "height" adjustment command to any running dialog causes a crash. Confirmed this is an issue in 2.4.1, 2.4.0 does not display this behavior.

@jeden-92 to side step this in the mean time, you can adjust that script to have the initial dialog set to the desired height and comment out the line with `echo "height: 600" >> $commandLog`

**Comment by bartreardon** [comment]
cheers for that - I'll have a look and see what's causing the crash

**Comment by bartreardon** [comment]
solved it - came about due to a change where I moved the window management code out of the SwiftUI app lifecycle and into an AppDelegate. In that context, the main observable object that contains the app state is not available and the `mainWindow` object doesn't get set. 

Probably needs some more cleanup as I think that variable now goes unused but works in limited testing.

**Comment by Bearzooka** [comment]
Probably it's obvious (being part of the `mainWindow` code) but worth mentioning that this happens as well if the `width` of the window is changed.
