### ISSUE TITLE
Add ability for all buttons to return json results...not just button 0

### ISSUE THREAD

**Issue by bartreardon** [swiftDialog/swiftDialog#360]
### Discussed in https://github.com/swiftDialog/swiftDialog/discussions/359

<div type='discussions-op-text'>

<sup>Originally posted by **LtCmdrScott** April  5, 2024</sup>
An added feature would be nice to have any button press return selection results (not just button 0).  for some reason, I cannot upload my image for reference, but I have a backup / restore routine that has someone choose a file location (Network, USB, etc) (radio button selection) and then button 0 is "backup" and button 1 is "restore", but obviously if they choose button 1, no results are returned as it is being treated as an Esc / Cancel</div>

**Comment by bartreardon** [comment]
Scope here for more generalised improvements to how buttons work, which have largely remained the same since the very first version

**Comment by wakco** [comment]
I'd add Radio buttons or a menu for Backup/Restore selection, then have button 0 be either Go or Okay, while button 1 remains as Cancel. (also added to discussion).

**Comment by bartreardon** [comment]
implemented in v2.5.0 with `--alwaysreturninput` argument.
