### ISSUE TITLE
swiftDialog Beta 2.5 - Using timer and hidetimerbar parameters disables the button entirely

### ISSUE THREAD

**Issue by stegray93** [swiftDialog/swiftDialog#368]
**Describe the bug**
When running the two parameters together, the button never enables. 

**To Reproduce**
dialog --title "hello" --button1text "ok" --timer 60 --hidetimerbar

**Expected behavior**
Unable to use button, must wait for timeout to occur. 

**Desktop (please complete the following information):**
 - 14.4.1
 - Dialog - 2.5.0.4757

**Comment by bartreardon** [comment]
this is related to #364
