### ISSUE TITLE
swwiftDialog 2.5 betas - {computermodel} variable does not display on Intel Mac models

### ISSUE THREAD

**Issue by mm2270** [swiftDialog/swiftDialog#371]
**Describe the bug**
I've found when testing out some of the new features in the 2.5 betas that the newly built-in `{computermodel}` variable does not display anything on any of the Intel Mac models I've tested it with. It does display the model on arm64 Macs though. Something about how it's pulling that information on the different architectures doesn't play nice on the older Macs.

**To Reproduce**
1. If you have an Intel Mac model, run `dialog --message "Mac model: {computermodel}"`
2. If my bug report is correct, it will only show "Mac model:" as the displayed text.
3. Repeat the same command on an M1/M2/M3 Mac, and the message display will be something like "Mac model: MacBook Pro (2021) 16-inch"

**Expected behavior**
That the model information would also be shown on older Mac models, since swiftDialog can still be used on these Macs.

**Screenshots**
<img width="932" alt="Screenshot 2024-05-04 at 9 53 18 PM" src="https://github.com/swiftDialog/swiftDialog/assets/3653600/677de6a8-790d-4dbb-9bb7-6fefef49a726">

**Desktop (please complete the following information):**
 - macOS version: 14.4.1
 - swiftDialog version: 2.5.0.4758
 
All the other variables seem to work fine on both architectures. It's just the computer model one that only seems to work on the arm64 devices.

**Comment by bartreardon** [comment]
ah yeah, thanks for the reminder. The process to get the machine model from an intel device is different from apple silicon (go figure) - I have the code for it, just haven't inserted it to the right place 🙂

**Comment by bartreardon** [comment]
addressed in 2.5.0 release
