### ISSUE TITLE
Ability to resize the message height

### ISSUE THREAD

**Issue by danielangeloni** [swiftDialog/swiftDialog#376]
First of all just wanna say this is a great project! I am looking at implementing it for my organisation as an alternative to DEPNotify. I will also look into if it's possible for me to make the script publicly available for others to use once it is finished.

**Is your feature request related to a problem? Please describe.**
When I have textfields and checkboxes and a somewhat long message (many new lines), it seems that there is an unnecessary amount of padding added above the textfields, or the message box doesn't expand to fill the available space.

**Describe the solution you'd like**
I'm not sure if it would be better to have a way to set the padding of the textfield elements group or to set a height of the message box, like a minimum height or something.

**Describe alternatives you've considered**
I looked through the docs and couldn't see much that I could use to resolve this, there doesn't appear to be a way to set the height of the message box
I tried playing around with the height of the dialog box a bit, removing and adding "big" but didn't really change much, neither did changing the height value. 

**Additional context**
Our environment has two possibilities for checkboxes and textfields being displayed. The more I have the more prevalent the issue becomes

Screenshot with 3 textfields and checkboxes combined:
<img width="1792" alt="Screenshot 2024-05-14 at 10 35 30 AM" src="https://github.com/swiftDialog/swiftDialog/assets/84752451/fb76da37-1408-476e-87d8-c76bafeeebfb">
<img width="1792" alt="Screenshot 2024-05-14 at 10 35 31 AM" src="https://github.com/swiftDialog/swiftDialog/assets/84752451/107a8434-8cf3-4aea-a4dd-7e8cafb6f0d2">

Screenshots with 4 textfields and checkboxes combined:
<img width="1792" alt="Screenshot 2024-05-14 at 10 33 41 AM" src="https://github.com/swiftDialog/swiftDialog/assets/84752451/ff214c3c-1e33-47b0-be23-365101ba843c">
<img width="1792" alt="Screenshot 2024-05-14 at 10 33 44 AM" src="https://github.com/swiftDialog/swiftDialog/assets/84752451/a600ac7e-8814-4027-b565-aca005293454">

Basically from the screenshots you can see the message box height is pretty small and starts showing the scroll bar too soon

Here is my json config 
```json
{
    "bannertitle": "UTS - Staff Provisioning Workflow",
    "titlefont": "shadow=1",
    "bannerimage": "/Users/<removed>/Library/Application Support/com.jamfsoftware.selfservice.mac/Documents/Images/brandingheader.png",
    "overlayicon": "/Applications/Self Service.app",
    "helpmessage": "<removed>",
    "buttonstyle": "center",
    "button1text": "Start Configuring my Mac",
    "big": true,
    "width": 900,
    "height": 600,
    "quitoninfo": 0,
    "ontop": true,
    "quitkey": "k",
    "icon": "SF=laptopcomputer.and.arrow.down,weight=semibold,colour1=#ef9d51,colour2=#ef7951",
    "message": "## Welcome to your new Mac! <br> <br>This Mac currently has **100%** of battery charge.  <br> <br>This Mac is currently connected to Ethernet. The connection is **lightning fast** and **stable**. The workflow might take a little longer than expected to complete. <br> <br>&nbsp; <br><br> To continue, please enter the following details about this computer",
    "infobox": "This workflow is currently applying a **UTS - Staff** build. <br><br> If this has started in error, please allow it to complete and contact your IT Support Team. ",
    "textfield": [
        {
            "title": "Asset Tag and Computer Name",
            "secure": false,
            "required": true,
            "prompt": "Please enter the Computer Name and Asset Tag",
            "regex": "<removed>",
            "regexerror": "<removed>"
        }
    ],
    "textfieldlivevalidation": true,
    "selectitems": [
        {
            "title": "Department",
            "values": ["<removed>"],
            "required": true
        }
    ],
    "checkbox": [
        {
            "label": "If no errors occur, automatically restart when provisioning workflow completes"
        }
    ],
    "checkboxstyle": {
        "style": "switch",
        "size": "regular"
    }
}
```

**Comment by mhrono** [comment]
I've been seeing behavior like this too, except in my case it's with _small_ messages. There's a bunch of padding added underneath the message area that ends up consuming ~50% of the total content space. Unfortunately, the change added to the latest RC doesn't appear to have changed anything on this end. :(

**Comment by bartreardon** [comment]
@mhrono if you can supply example screenshots and commands to replicate I can take a look. include `--infotext` and `--debug` which will show some extra detail on the dialog that can help me diagnose.
