### ISSUE TITLE
Clicking Notification results in other dialog window closing

### ISSUE THREAD

**Issue by BigMacAdmin** [swiftDialog/swiftDialog#378]
**Describe the bug**
If a user clicks a dialog notification, another dialog window is closed with exit code 0

**To Reproduce**
1. Run this example script, and click the notification while the dialog window is open
```bash
#!/bin/bash
#set -x

# Dialog bug example

# First call a notification...
/usr/local/bin/dialog --title "Bugs" --message "Better than snakes, I guess..." --notification

# Now call a dialog window
/usr/local/bin/dialog --title "Bugs" --message "Better than snakes, I guess..." --icon "text=🐞"
exitCode=$?
echo "Exit code: $exitCode"

# Observe that if the notification is clicked, the dialog window exits with code 0
```

**Expected behavior**
Clicking the notification should not close open dialog windows.

**Desktop (please complete the following information):**
 - macOS version `14.5`
 - swiftDialog version `2.4.2.4755` as well as `2.5.0.4758`
 -

**Comment by dan-snelson** [comment]
@BigMacAdmin:

What if you used unique command files?

**Comment by BigMacAdmin** [comment]
> @BigMacAdmin:
> 
> What if you used unique command files?
Does not appear to get around the issue

**Comment by bartreardon** [comment]
Ooh good catch. This is an issue in that every instance of dialog watches for notifications. I need to adjust so only instances activated by the notification service responds to notification actions.
