### ISSUE TITLE
Cannot use button 2 or button 3 without entering text into required fields

### ISSUE THREAD

**Issue by BigMacAdmin** [swiftDialog/swiftDialog#380]
**Describe the bug**
This is probably broken due to my recent feature request, and the issue is not present on v2.4.2. 

Previously, if `--textfield "Something",required` was used, the requirement was not enforced if the user clicks button 2 or info button. With Dialog v2.5.0.4758 , the required field is requiring input even to use those buttons.

**To Reproduce**
1. Install beta 2.5.0
2. Run `/usr/local/bin/dialog --title "This is why we can't have nice things" --message " " --button2text "Can't Cancel" --infobutton "Can't Info" --textfield "Tell me something",required`
3. Try to click button 2 or 3

**Expected behavior**
Cancelling the dialog or clicking the info button should not require data entry for a `required` textfield.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version 14.5
 - swiftDialog version `2.5.0.4758`

**Comment by bartreardon** [comment]
hmm - I don't think it's related to your change. Likely #360

**Comment by BigMacAdmin** [comment]
Hmmm, seems bad. Also, json results were not being returned even when I did put in a value and click button2.
