### ISSUE TITLE
Boolean options with JSON config are not respected

### ISSUE THREAD

**Issue by mhrono** [swiftDialog/swiftDialog#381]
**Describe the bug**
After noticing some odd behavior with the info button not being hidden when expected, I went to Slack for confirmation (thread linked at the bottom). After discussion, it seemed as if I was specifying my JSON options using an old (now fixed) method where swiftDialog could misinterpret integers in JSON configurations. Long story short, I went in and updated my code to use true JSON boolean values instead of 0/1. Unfortunately, it seems these are not being respected across the board.

After some additional testing, I can confirm the following JSON options are not respected when specified using true/false boolean values:
- button1disabled
- infobutton
- quitoninfo
- ontop
- moveable
- hideicon

**To Reproduce**
Sample JSON that will reproduce the issue below. Flip any specified boolean value and observe that the behavior of the generated dialog does not change. This JSON was generated as part of a [swiftPatch](https://github.com/mhrono/swiftpatch) run with Python 3.12.1. The issue also presents when dialog is called directly from a zsh terminal.

```
{
  "title": "Managed App Updates Available",
  "titlefont": "size=20",
  "messagefont": "size=14",
  "messageposition": "top",
  "position": "topright",
  "button1text": "Update Selected",
  "button1disabled": false,
  "timer": "300",
  "infobutton": false,
  "quitoninfo": false,
  "ontop": true,
  "moveable": false,
  "quitkey": "i",
  "json": true,
  "checkboxstyle": {
    "style": "switch",
    "size": "small"
  },
  "checkbox": [
    {
      "label": "1Password | v8.10.33 ➡ v8.11.33",
      "checked": true,
      "disabled": false,
      "icon": "/Applications/1Password.app"
    }
  ],
  "message": "**App to be Quit and Updated                                                              Update Now?**",
  "messagealignment": "center",
  "hideicon": true,
  "width": "550",
  "selectitems": [
    {
      "title": "Defer Unselected Apps:",
      "required": false,
      "values": [
        "5 minutes",
        "15 minutes",
        "1 hour",
        "3 hours",
        "1 day"
      ]
    }
  ]
}
```

**Expected behavior**
Boolean options for dialog behavior should be respected.

**Screenshots**
Using the above JSON, the dialog shown below is generated. Notice that `button1disabled`, `infobutton`, and `hideicon` are each behaving counter to their configured JSON settings.

<img width="662" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/37225540/17182c5e-b760-482e-a26b-9baf1ff482df">

**Desktop (please complete the following information):**
 - macOS version: 14.5
 - swiftDialog version: 2.4.2

**Update:** After trying several versions, I've found that this bug was introduced with dialog 2.4.0. Hopefully this helps!

**Additional context**
[#swiftdialog thread](https://macadmins.slack.com/archives/C01U5MXNGG6/p1716414582174449)

**Comment by bartreardon** [comment]
fixed in v2.5.0
