### ISSUE TITLE
Spashscreen status updates question

### ISSUE THREAD

**Issue by ashorinx13** [swiftDialog/swiftDialog#383]
Hello,

I'm working on deploying onboarding splash screen following this and all worked great until I started to add more scripts, while they work and software is getting installed - I cannot figure out what controls status change in the splash screen, new scripts stuck in Pending status. 

I thought waitForSplashScreen=true  SplashScreenProcess="Dialog" in the script controls this behaviour but so far had no luck, am I 
missing something?                                                
[07-installMinecraftEE.zip](https://github.com/swiftDialog/swiftDialog/files/15491527/07-installMinecraftEE.zip)

The script that I'm using attached, and I would really appreciate any advice.

**Comment by acodega** [comment]
Did you mean to post to a different repository? While this script uses swiftDialog, it sounds like the issue should be addressed by the script maker.

**Comment by bartreardon** [comment]
yeah, none of those are swiftdialog options. You'll need to contact whoever wrote the splash screen thing

**Comment by ashorinx13** [comment]
Sorry gents, I'll post there
