### ISSUE TITLE
Icon placement behaving in unexpected ways in 2.5.0-4762

### ISSUE THREAD

**Issue by BigMacAdmin** [swiftDialog/swiftDialog#385]
**Describe the bug**
In v.2.5.0-4762 I observed a missing icon while running a script, and tested the same script in v.2.4 which is working as expected.

**To Reproduce**
1. Run this command in both v2.4 and v2.5 and observe the differences:
```bash
    /usr/local/bin/dialog \
        --title none \
        --message " " \
        --icon "SF=magnifyingglass.circle" \
        --progress \
        --moveable \
        --ontop \
        --width 420 \
        --height 150 \
        --centericon \
        --button1disabled 
```
**Expected behavior**
The icon should be rendered as it is in v2.4

**Screenshots**
v.2.4
![2 4](https://github.com/swiftDialog/swiftDialog/assets/106293503/5f01ce22-8f02-4652-9d3e-03a60c498fd3)

v.2.5
![2 5](https://github.com/swiftDialog/swiftDialog/assets/106293503/e41bfc65-414c-4dd9-ba60-e19e8657fa7b)

**Desktop (please complete the following information):**
 - macOS version 14.5
 - swiftDialog version `2.5.0-4762`

**Additional context**
1. Issue appears to only take effect when reducing the window size
2. In both 2.4 and 2.5, if we use the `--centericon` feature along with `--message none` we get a much different icon location than if we use `--message " "`. Using `--message none` appears to align the icon right instead of center.

**Comment by bartreardon** [comment]
yeah, weird. comparing everything between 2.4.2 and 2.5 there's nothing in those views that should have resulted in how that view was displayed, unless it was a change in an update to MarkdownUI that caused empty strings `" "` to result in a zero width view.

In any case, it's being forced into submission now.

**Comment by BigMacAdmin** [comment]
The build you posted on Slack `2.5.0-4763` did solve the problem.

One apparent side effect, which you may or may not care about, is that the icon is now much smaller by default than it was in v2.4

Using the same command as above, testing with an SF symbol as well as an .app path:

![2 4-appicon](https://github.com/swiftDialog/swiftDialog/assets/106293503/4917e513-3260-44db-8f81-bb5eb55ae346)
![2 5-appicon](https://github.com/swiftDialog/swiftDialog/assets/106293503/f458a61b-68f5-464f-a4f2-e208269aa5f1)

![2 5-sf](https://github.com/swiftDialog/swiftDialog/assets/106293503/1db3f755-71b4-4ee9-8892-cd00c400ac0b)
![2 4-sf](https://github.com/swiftDialog/swiftDialog/assets/106293503/c754fa9b-9b8c-48ac-be04-f5c7bc18f545)
