### ISSUE TITLE
ERROR: Couldn’t communicate with a helper application via JAMF

### ISSUE THREAD

**Issue by GoodDayStudio** [swiftDialog/swiftDialog#392]
Getting this error when trying to push via script in JAMF.  I have tried both policy with script at recurring interval, using Files and Process to call a policy and using Files and Process to call dialog directly using the command below.

`/usr/local/bin/dialog --notification --title "Restart Required" --message "A script was run on your computer.  Please restart your computer for it to take effect."`

Works fine when calling the policy from terminal on the local machine and using the command above on the local machine.

I have also noticed that it seems to work just fine on Intel Macs.  Only started having this issue after updating to 14.4+ on my Silicon users.

<img width="490" alt="Screenshot 2024-06-06 at 4 21 48 PM" src="https://github.com/swiftDialog/swiftDialog/assets/171987081/ba98cf88-8756-4cdb-9dac-615ce15f1616">

 - macOS version 14.4, 14.4.1, 14.5
 - swiftDialog version 2.4.1.4754

Related to #219.  Something about not liking being called by root but not sure how to resolve that when the script is coming from JAMF...

**Comment by bartreardon** [comment]
it's exactly #219 - jamf policies run from launchd are not in the same context when they are run manually so you need to fix that.

**Comment by GoodDayStudio** [comment]
I haven't had any issues until we updated to 14.4+.  I have read #219 and believe I am following the methods suggested.  And it works fine on my Intel Macs from what I can tell.  Any suggestions or clarity on how I should fix this as you describe?  I don't fully understand what I would need to do in order to fix that.

**Comment by bartreardon** [comment]
I don't know what to suggest since I don't know what your environment looks like, if you running jamf on-prem, what version you're on etc. Have you tried triggering the notification a different way etc (e.g using a script instead of files and processors).

Basically the issue is how jamf runs the app, not how swiftDialog works. There's some consideration to make it work but that's not bulletproof so you'll need to dig under the hood of how you're asking jamf to run things.

**Comment by dan-snelson** [comment]
@GoodDayStudio: On the off-chance the following proves helpful:

[Actionable, Custom Branded macOS Notifications with swiftDialog 2.4.0](https://snelson.us/2024/02/actionable-custom-branded-macos-notifications-with-swiftdialog-2-4-0/)

**Comment by dan-snelson** [comment]
And / or [Display Message (0.0.8) via swiftDialog](https://snelson.us/2023/03/display-message-0-0-7-via-swiftdialog/)

**Comment by GoodDayStudio** [comment]
I appreciate the replies!

I use Jamf Cloud server.  I have tried triggering Dialog via Script, Files and Processes, local direct and local jamf policy.  Only options that work are local from users terminal.  I had it fully working until we did a MacOS update.  So I will try to wipe and redeploy next week and let you know what comes of it.

**Comment by bartreardon** [comment]
all good 🙂
