### ISSUE TITLE
Stacked button style breaks timers

### ISSUE THREAD

**Issue by nstrauss** [swiftDialog/swiftDialog#401]
**Describe the bug**
When using the `--timer` argument with `--buttonstyle "stack"`, timers break.

**To Reproduce**
Use the timer and buttonstyle stack arguments together. The timer never starts, and button 1 remains grayed out forever. Adding `hidetimerbar` allows for the button to be clickable, but the timer never triggers which in turns keep the window open.

`dialog --message "Hello world" --button1text "OK" --timer 10`
![image](https://github.com/swiftDialog/swiftDialog/assets/17690356/ba3bf31d-50a6-4585-92c5-57b50031fa13)
`dialog --message "Hello world" --button1text "OK" --timer 10 --buttonstyle "stack"`
![image](https://github.com/swiftDialog/swiftDialog/assets/17690356/1f51c605-7486-4ec2-a5c7-ccc698aaa6ab)
`dialog --message "Hello world" --button1text "OK" --timer 10 --buttonstyle "stack" --hidetimerbar`
![image](https://github.com/swiftDialog/swiftDialog/assets/17690356/f88ac2fe-c846-4ce9-b4fe-c42ef7da4f49)

**Expected behavior**
The dialog window should close after the timer expires.

**Desktop (please complete the following information):**
 - macOS 14.5
 - swiftDialog 2.5.0.4768

**Comment by jonesiscoding** [comment]
It looks like this behavior is the same with `--buttonstyle center` and `--timer` used together.  

Looking at the code, the timer bar is never drawn in the view when using a `buttonstyle`.  This may be intentional in the `center` style, as the positioning of the timer bar is usually to the left of the buttons.

Depending on what @bartreardon thinks about the idea, it might be possible to add the timer bar when using `--buttonstyle stacked`, or this may just be something that needs to be updated in the documentation.

**Comment by jonesiscoding** [comment]
After doing some testing, I would be happy to submit a PR to allow `--buttonstyle stack` and `--timer` to be used together.   

As the timer bar fills the width of the window, implementing it with `--buttonstyle center` would probably not be very useful.

**Comment by nstrauss** [comment]
I was curious whether it was introduced with `stack` or related to an existing mode which doesn't support timers. @jonesiscoding Appreciate you taking the time to look into this. If you're open to a PR, please go ahead. I could poke at it as well in the next few weeks.

**Comment by jonesiscoding** [comment]
Will do - should have something a little later today, as it seemed pretty straightforward.

**Comment by bartreardon** [comment]
I'm happy for it to be implemented however if it looks nice. The OG timer appears between whatever buttons are being displayed so it acts as filler along the button area. With stacked and centred buttons the timer bar would need to be placed somewhere else. I'm semi-inclined to use this as an opportunity to re-think how the timer bar looks and is displayed but open to suggestions.

**Comment by jonesiscoding** [comment]
I have this working, but was waffling between two different styles, so haven't opened the PR yet.

With the stacked buttons I thought the progress bar might look slightly better if the corner radius matched the buttons, however, Apple's UI guidelines seem to always show a progress bar rounded. 

If there's a preference, let me know and I'll commit and open the PR.  

### Timer Corner Radius Matching Buttons

<img width="932" alt="swiftdialog-timer-left" src="https://github.com/swiftDialog/swiftDialog/assets/5215554/33d9988c-1d41-4a9a-8f38-c4c9651a4774">

<img width="412" alt="swiftdialog-timer-center" src="https://github.com/swiftDialog/swiftDialog/assets/5215554/c761542d-f86e-4f6f-b745-cc56306f8e13">

### Timer Corner Radius Rounded

<img width="932" alt="swiftdialog-timer-stack-rounded-left" src="https://github.com/swiftDialog/swiftDialog/assets/5215554/b2111dbb-e264-4e07-a4c4-ab2c95bb7872">

<img width="412" alt="swiftdialog-timer-stack-rounded-center" src="https://github.com/swiftDialog/swiftDialog/assets/5215554/e080bed9-6225-48cb-a24b-ae3ecc9f0a3e">

**Comment by bartreardon** [comment]
looks good 🙂 

I'm not sure if there is a hig about where buttons should be placed in relation to other UI elements but given the timer is not interactive having it underneath makes sense. 

@jonesiscoding if you pr this into main I'll change the branch and add it as a fix in 2.5.1 (when I get around to creating it)

**Comment by jonesiscoding** [comment]
Sounds good - I'll create the PR this evening.  

My apologies for the delay - I'm a little behind as we were given short-notice of a full-shutdown power maintenance window for this Saturday.

**Comment by bartreardon** [comment]
NP - I'm behind on a bunch of stuff as well. Should be able to look into it over the next couple of weeks though if you have time

**Comment by bartreardon** [comment]
pretty sure this one was released in v2.5.1
