### ISSUE TITLE
Presentation mode is missing checkboxes

### ISSUE THREAD

**Issue by Doronkerub** [swiftDialog/swiftDialog#406]
it looks like the new `--presentation` mode is lacking the option to use checkboxes
for example- running `dialog --presentation --checkbox "This is a test"` will result in the following dialog:
![CleanShot 2024-07-09 at 09 45 24](https://github.com/swiftDialog/swiftDialog/assets/112400624/18cc6c2b-878e-42e7-a1e1-ef704b88c90b)

the checkbox is missing, but SwiftDialog will return a "false" status for it when closing the dialog

**Comment by bartreardon** [comment]
correct - [as per the wiki](https://github.com/swiftDialog/swiftDialog/wiki/Presentation) "Presentation mode is an output only (no user input) mode of swiftDialog intended for displaying an ongoing process or task." 

Emphasis on "no user input" which would include checkboxes 🙂
