### ISSUE TITLE
5302 Illegal instruction: 4

### ISSUE THREAD

**Issue by Mac-Gripp** [swiftDialog/swiftDialog#412]
With OS 12.6.6( it's a test machine for OS-updates):

**Version 2.5.0.4768** 
works not:
dialog --message "test"
/usr/local/bin/dialog: line 58: 5302 Illegal instruction: 4 "$dialogbin" "$@"

works fine:
dialog --title "test"

**Installed 2.4.2.4755** and it works all. I think it is a bug

**Comment by bartreardon** [comment]
this is already reported under #386

**Comment by bartreardon** [comment]
Fixed in https://github.com/swiftDialog/swiftDialog/releases/tag/v2.5.1
