### ISSUE TITLE
Crash when updating message if a list is present

### ISSUE THREAD

**Issue by FourCheeseMac** [swiftDialog/swiftDialog#415]
**Describe the bug**
On 15.0 B3, If you have a dialog with `list:` item added, and then update the `message:`, Dialog crashes.
This behavior is not being seen on 14.5 or previous OS's

**To Reproduce**
```
dialog &
echo 'listitem: add, title: hi' >> /var/tmp/dialog.log
echo 'list: show' >> /var/tmp/dialog.log  
echo 'message: A test message' >> /var/tmp/dialog.log
```

This will cause `/usr/local/bin/dialog: line 58: 75605 Trace/BPT trap: 5       "$dialogbin" "$@"` to be printed to console and Dialog to crash.

**Expected behavior**
Does not crash :)

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: 15.0 B3
 - swiftDialog version: 2.5.0.4768

**Comment by FourCheeseMac** [comment]
@BigMacAdmin  -- Good callout, I'll edit the report, but we're not seeing the behavior on 14.5 or other previous OS's.
Only seeing on 15.0 B3 so far.

**Comment by aanklewicz** [comment]
I ran @BigMacAdmin's script and it crashed for me with the following errors. 

`2024-07-17 13:35:07.213 Dialog[32705:1229453] +[IMKClient subclass]: chose IMKClient_Legacy
2024-07-17 13:35:07.213 Dialog[32705:1229453] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
[/usr/local/bin/dialog: line 58](coderunner:///usr/local/bin/dialog#58:0!): 32705 Trace/BPT trap: 5       "$dialogbin" "$@"`

Swift Dialog 2.5.0.4768
macOS 15.0 Beta (24A5289h)
Executing Script in CodeRunner Version 4.3 (67365)

**Comment by bartreardon** [comment]
Fixed in https://github.com/swiftDialog/swiftDialog/releases/tag/v2.5.1
