### ISSUE TITLE
--centreicon aligns icon to right hand margin when "--message none" is used

### ISSUE THREAD

**Issue by philipross** [swiftDialog/swiftDialog#419]
**Describe the bug**
When using `--message none` and `--centreicon` are used concurrently, the icon is aligned to the right hand side of the dialog window.

**To Reproduce**
Run: `dialog --centreicon` : no other parameters, and the icon is centred correctly.
Then run: `dialog --centreicon --message none` : the icon is then aligned to the right hand side of the box.

Note, this also happens on `--centericon` - but I think that's probably to be expected if the arguments are aliases of one another.

**Expected behavior**
The icon is centred

**Screenshots**
Screenshots provided below.

**Desktop (please complete the following information):**
 - macOS version: 14.5
 - swiftDialog version: 2.5.0.4758

<img width="1087" alt="Screenshot 2024-07-22 at 18 12 47" src="https://github.com/user-attachments/assets/b6399ffb-a3eb-413f-978b-3428260053e7">
<img width="1139" alt="Screenshot 2024-07-22 at 18 13 22" src="https://github.com/user-attachments/assets/258f453a-9faf-4114-a4ca-dfd1cce746bc">

**Comment by bartreardon** [comment]
`2.5.0.4768` is the latest version and does not exhibit this behaviour

`2.5.0.4758` was Beta release.
