### ISSUE TITLE
What would cause dialog to return 141 and not display a dialog.

### ISSUE THREAD

**Issue by DirkM20** [swiftDialog/swiftDialog#420]
In my script, dialog 2.5.0 is returning 141 instead of displaying the dialog. This happens randomly, not reproducible on purpose.

This happens with a "blank" dialog call where /usr/local/bin/dialog is called without any parameters.

What would cause dialog to return 141 without displaying a dialog?

**Comment by bartreardon** [comment]
That depends. what version of macOS are you running this on and what type of actions are you trying to perform?

**Comment by bartreardon** [comment]
Fixed in https://github.com/swiftDialog/swiftDialog/releases/tag/v2.5.1
