### ISSUE TITLE
Feature request: set/override a dialogs dark or light mode.

### ISSUE THREAD

**Issue by wakco** [swiftDialog/swiftDialog#421]
There is no way to set the light or dark mode of Apples login window, therefore a `--loginwindow` over the login window, is always in light mode, I'd like to be able to override that.

A setting that can be set to auto, dark, or light from the command line, command file, json, or json file that would tell swift dialog which mode to operate in. i.e. `--appearance-mode dark`

**Comment by bartreardon** [comment]
Thought about this for a bit and sorted out a nice implementation (I think)

`--mode [dark|light]` will enforce the chosen appearance 

I also added an implementation for specifying an optional alternate icon resources for dark mode using a `:dark=` modifier

`--icon /path/to/icon.png:dark=/path/to/dark_icon.png`

should work wherever icon resources are accepted.

**Comment by bartreardon** [comment]
Fixed in https://github.com/swiftDialog/swiftDialog/releases/tag/v2.5.1
