### ISSUE TITLE
Location of Check boxes and Text Fields

### ISSUE THREAD

**Issue by peavine** [swiftDialog/swiftDialog#429]
**Is your feature request related to a problem? Please describe.**
No. The app works great

**Describe the solution you'd like**
I use a swiftDialog dialog that contains both textfields and checkboxes. The checkboxes are displayed before the textfields, and, just as a matter of personal preference, I would prefer it to be the other way around. 

**Describe alternatives you've considered**
I read the documentation but couldn't find an alternative.

**Additional context**
The dialog is used in an AppleScript on a Sonoma computer. I've included a screenshot of the existing dialog below.

![Search and Replace](https://github.com/user-attachments/assets/b3b0b511-47ab-410d-a84b-9777722c6808)

**Comment by bartreardon** [comment]
beat me to it @acodega 🙂  - did I not update the wiki? I should fix that.

**Comment by peavine** [comment]
Thanks for the responses. The --vieworder option is in the documentation, and it works great. Sorry about that!
