### ISSUE TITLE
Size of textfield box in which the user enters text

### ISSUE THREAD

**Issue by peavine** [swiftDialog/swiftDialog#432]
**Is your feature request related to a problem? Please describe.**
There seems to be a difference in the manner in which a text field is displayed as shown in the screenshot below and as it is shown in the swiftDialog wiki.

**Describe the solution you'd like**
I would prefer that the box that contains the entered text extend all the way to the left to the textfield label.

**Describe alternatives you've considered**
I changed the width of the dialog as a partial workaround.

**Additional context**
I carefully read all the documentation and looked at all issues. I hope I didn't miss anything. I have a 2023 Mac mini running the current versions of Sonoma and swiftDialog. Thanks for the great app--I  have already made extensive use of it in numerous scripts.

![swiftDialog](https://github.com/user-attachments/assets/b355ee52-2217-4818-a1ab-511ac95c5057)

**Comment by bartreardon** [comment]
> There seems to be a difference in the manner in which a text field is displayed as shown in the screenshot below and as it is shown in the swiftDialog wiki.

Can you link in the wiki where it it different to what you are expecting?

**Comment by peavine** [comment]
The link is:

https://github.com/swiftDialog/swiftDialog/wiki/Textfields

A screenshot:

![Text Field](https://github.com/user-attachments/assets/6d6ee334-00ea-44a7-85de-3abf74a8a6f0)

**Comment by bartreardon** [comment]
ah - yeah, there is a maximum size set on the textfield size. If the window is small enough and the label is long enough then these will meet in the middle somewhere but for larger dialogs they will seperate. The label is left justified and the text box is right justified.

**Comment by peavine** [comment]
Thanks for the explanation.
