### ISSUE TITLE
Spelling error in https://github.com/swiftDialog/swiftDialog/wiki/Info-Box

### ISSUE THREAD

**Issue by Honestpuck** [swiftDialog/swiftDialog#436]
**Describe the bug**
On the wiki page https://github.com/swiftDialog/swiftDialog/wiki/Info-Box you will find that in the example "Additional" is spelt "Aditional"

**Additional Content**
(If wikis could be forked I'd have done a PR. Bad GitHub, bad!)

**Comment by BigMacAdmin** [comment]
I fixed it because Bart deserves to have 60 seconds of his day saved. Thanks!

**Comment by bartreardon** [comment]
they can be but it's such a pain in the arse to do

**Comment by bartreardon** [comment]
@BigMacAdmin FTW 🙂
