### ISSUE TITLE
File Select window hidden behind Dialog

### ISSUE THREAD

**Issue by ccwcfl** [swiftDialog/swiftDialog#441]
**Describe the bug**
When using the blurscreen flag and you have file select as an option, the window will be stuck behind the Dialog window. You have to press escape to close the file browser to interact with the Dialog screen again

While the file select is active, you cannot interact with the Dialog window, and any updates are not shown. If you press escape it will update to the proper state.

**To Reproduce**
1. Create JSON file and activate as normal with the blurscreen flag to true and a fileselect option
2. Run Dialog command
3. Click to select a file/folder

Example json:
```
{
    "title" : "Folder Selection",
    "moveable" : true,
    "height" : "700",
    "width" : "900",
    "button1text" : "OK",
    "button1disabled" : false,
    "button2text" : "Cancel",
    "button2disabled" : false,
    "blurscreen" : true,
    "message" : "Please select a folder to save your document to",
    "textfield" : [
        {
            "title" : "Folder Location",
            "fileselect" : true,
            "filetype" : "folder"
        }
    ]
}
```

**Expected behavior**
Finder window to show in front of the Dialog prompt

**Screenshots**

![Cleanshot 2024-09-26 at 13 23 07 - CleanShot](https://github.com/user-attachments/assets/801c0408-aa25-4a26-aac5-5503f95c85f5)

**Desktop (please complete the following information):**
 - macOS version: 14.4.1 and 15.1
 - swiftDialog version 2.5.2.4777

**Comment by FranckSartori** [comment]
I will look at this as even when `--blurscreen` is not enabled, the file selector is displayed behind the Dialog.
