### ISSUE TITLE
The --loginwindow feature might need something extra for working after boot.

### ISSUE THREAD

**Issue by wakco** [swiftDialog/swiftDialog#442]
The `--loginwindow` feature has trouble working after the computer boots, but always works after someone logs out. Per elios on the #outset MacAdmins slack channel Munki appears to have the solution in the [main.swift](https://github.com/munki/munki/blob/main/code/apps/MunkiStatus/MunkiStatus/main.swift) file (the while loop).

So I'm wondering if that could be implemented in the `--loginwindow` feature?

**Comment by wakco** [comment]
And for those that don't want to follow the link...
```
//
//  main.swift
//  MunkiStatus
//
//  Created by Greg Neagle on 8/27/19.
//  Copyright © 2019-2024 The Munki Project. All rights reserved.
//

import Cocoa

// On Catalina, LaunchAgents run under "LimitLoadToSessionType : LoginWindow" on
// boot seem to be run before a CGSession is setup. Wait until the session is
// available before handing execution over to NSApplicationMain().
// Thanks to Tom Bergin for this insight.
while CGSessionCopyCurrentDictionary() == nil {
    print("Waiting for a CGSession...")
    usleep(500000)
}
<snip>

```

**Comment by bartreardon** [comment]
Sounds good.

I'm thinking that we could start just implying `--loginwindow` all the time rather than specify it as an argument that puts swiftdialog into some state. In my testing there's no performance impact

**Comment by fraserhess** [comment]
As coded at the moment passing `--loginwindow` implies `--ontop` which is needed to display above the login window.
To remove the need for `--loginwindow`, (meaning the windows all have `canBecomeVisibleWithoutLogin` set to `true` regardless) either:
a) All dialogs displayed at the login window need an explicit `--ontop`
b) the login window environment is detected (not sure how) and window level set accordingly

**Comment by wakco** [comment]
needed somewhere to put this, but since a shell script can't check `CGSessionCopyCurrentDictionary` for itself, I started looking for other options to make sure my zsh shell script did the same thing, and came across a use of `ioreg` that pointed me in an interesting direction, so after testing found watching for the existence of `kCGSSessionSecureInputPID` does the trick:

```
while [ "$( /usr/libexec/PlistBuddy -c "print :IOConsoleUsers:0:kCGSSessionSecureInputPID" /dev/stdin 2>/dev/null <<< "$(ioreg -n Root -d1 -a)" )" = "" ]; do
 sleep 0.2
done

```
