### ISSUE TITLE
Return Output with More Information Button

### ISSUE THREAD

**Issue by peavine** [swiftDialog/swiftDialog#443]
**Is your feature request related to a problem? Please describe.**
I occasionally need to have a dialog with 3 buttons. On some occasions, I can use the more information button for this purpose, but this doesn't work when I need to get output (see screenshot example below). 

**Describe the solution you'd like**
My request is an option to get output when the more information button is selected. 

**Describe alternatives you've considered**
This can be done with radio buttons, but that's not a good solution in all instances.

**Additional context**
The following is a screenshot of an example in the Shortcuts app. Thanks for the great app.

![swiftDialog](https://github.com/user-attachments/assets/cd986f59-b5c0-4645-948a-316344f708a9)

**Comment by bartreardon** [comment]
this is already available with the `--alwaysreturninput` argument

**Comment by peavine** [comment]
Thanks. I tested the `--alwaysreturninput` argument and that's just what I need.
