### ISSUE TITLE
Use stacked buttons with alert style

### ISSUE THREAD

**Issue by jgates1** [swiftDialog/swiftDialog#446]
I would like to use `--style alert` with `--buttonstyle stack`. Currently, it is one or the other. Alert will always put them side-by-side but without alert, it will allow for buttons to stack. I put some examples before. If this intentional and I have completely missed the documentation, I apologize, I looked for any mention of this.

Examples:
**Using Alert and Stack:** 
![CleanShot 2024-10-08 at 12 58 00](https://github.com/user-attachments/assets/adfa08cd-a92c-4a3b-9d68-074091c33d27)
`/usr/local/bin/dialog --title "Ticket Created" \
                      --message " " \
                      --messagealignment center \
                      --button1text "View Ticket" \
                      --button2text "Close" \
                      --icon SF=checkmark.circle.fill,colour=#266838,weight=heavy \
                      --buttonstyle stack \
                      --appearance dark \
                      --style alert \
                      --ontop`

**Using Stack without Alert:**
![CleanShot 2024-10-08 at 12 56 35](https://github.com/user-attachments/assets/6349e5ac-f6f1-4b0e-b792-69acc24490d1)
`/usr/local/bin/dialog --title "Ticket Created" \
                      --message " " \
                      --messagealignment center \
                      --button1text "View Ticket" \
                      --button2text "Close" \
                      --icon SF=checkmark.circle.fill,colour=#266838,weight=heavy \
                      --buttonstyle stack \
                      --appearance dark \
                      --small \
                      --ontop`

**Comment by bartreardon** [comment]
the `alert` style is just a quick preset that displays a single button centred. It uses the same argument parameters that you would use on the command line, but with modified preset values

You can achieve the same results with the following:

```bash
dialog --buttonstyle stack --button1text "View Ticket" --button2text "Close" --centreicon --iconsize 80 --title none --messageposition centre --messagealignment centre --width 300 --height 300 --message "### Ticket Created" --icon SF=checkmark.circle.fill,colour=#266838,weight=heavy
```

**Comment by jgates1** [comment]
Thank you for getting back to me so quickly! I'll get this closed!
