### ISSUE TITLE
Allow `--helpmessage' to support markdown files

### ISSUE THREAD

**Issue by BigMacAdmin** [swiftDialog/swiftDialog#447]
**Is your feature request related to a problem? Please describe.**
I would like to implement a consistent "Help message" text across many swiftDialog windows/projects. Markdown files are not supported for `--helpmessage`

**Describe the solution you'd like**
Please allow us to pass file paths to markdown files 

**Describe alternatives you've considered**
Using `"$(cat "$pathToMDFile")"` in my scripts, however that gets difficult in the context of putting it in a Baseline configuration file

**Additional context**
![image](https://github.com/user-attachments/assets/24c5bed5-b2a8-48eb-9354-46589e1df215)

**Comment by bartreardon** [comment]
At first I was like "help message totally supports markdown" but then I read the rest :/ 

will take a look. should be an easy fix

**Comment by BigMacAdmin** [comment]
I was guessing it wasn't a huge ask, so I figured I would submit it :) Thanks, Bart.
