### ISSUE TITLE
Abliity to use Emojis in notifications

### ISSUE THREAD

**Issue by philipross** [swiftDialog/swiftDialog#454]
**Is your feature request related to a problem? Please describe.**
Amongst other things, I utilise Dialog notifications to send reminders to my end users devices when a software update is ready for them to self-install, through MDM self service, ahead of then an enforcement push from said MDM.
I tried today to include an emoji, like I've seen in other notifications from Applications such as Zoom, of an alarm clock - to highlight the urgency and time critical situation.
Unfortunately, Dialog rendered ⏰ as `:alarm_clock:` in both the `--title` and `--message` fields.

**Describe the solution you'd like**
I'm not sure how easy or feasible it would be to enable dialog notifications to present emojis, but that would be mega. 

**Describe alternatives you've considered**
None considered.

**Additional context**
Example screenshot shows a dialog notification (command was `dialog --notification --title "Time to go :alarm_clock"! --message "This is a clock :alarm_clock" ` compared to one from Zoom which did render the emoji.
<img width="332" alt="Screenshot 2024-10-28 at 09 19 46" src="https://github.com/user-attachments/assets/70756871-f00b-4c74-9701-16db205eed81">

**Comment by bartreardon** [comment]
:emojiname: isn't a format swiftdialog supports. Being up the emoji picker (cmd opt space i think. Or cmd control space) and use unicode amd it will work fine.

**Comment by bartreardon** [comment]
cool - I've always used control+command+space and it brings up the picker. never used fn key for it (aside, not sure why cis would recommend disabling that but then I'm not in a super strict environment so 🤷‍♂️)
