### ISSUE TITLE
Enable rounded corners for Base64-encoded images

### ISSUE THREAD

**Issue by zhorvath83** [swiftDialog/swiftDialog#456]
**Is your feature request related to a problem? Please describe.**
When using a square icon as a local file or through a URL reference, the image displays with nicely rounded corners. However, when the same image is used in Base64-encoded format, the rounded corner styling is not applied, resulting in inconsistent appearance across formats.

**Describe the solution you'd like**
Please add support for rounded corners on Base64-encoded images to provide a consistent visual style across all image formats.

**Additional context**
Please find a simple test script attached.
[dialog_b64_image_test.sh.zip](https://github.com/user-attachments/files/17569347/dialog_b64_image_test.sh.zip)
For security reasons, the Base64 string not included directly in the file.

**Comment by bartreardon** [comment]
LMK if the 2.5.3b3  release sorts it out

https://github.com/swiftDialog/swiftDialog/releases/tag/v2.5.3b3

**Comment by zhorvath83** [comment]
Thank you very much, the provided fix is perfect!
