### ISSUE TITLE
Overlay icon not rendered when `--centericon` is true

### ISSUE THREAD

**Issue by in03** [swiftDialog/swiftDialog#466]
**Describe the bug**
Overlay icons do not render when using the `--centericon` option.

**To Reproduce**
1. Install swiftDialog 2.5.3
2. Run this:
```shell
    /usr/local/bin/dialog command display alert \
    --title "Network Connection" \
    --message "### Test awdawd awd awd" \
    --messagealignment "center" \
    --icon "SF=network.slash" \
    --overlayicon "SF=xmark.circle.fill,colour=auto"\
    --bgcolour none \
    --button1disabled \
    --centericon \
    --width 500 \
    --height 300 \
```
3. Observe no overlay icon
4. Install swiftDialog 2.5.2
5. Run the above again
6. Observe overlay icon alive and well

**Expected behavior**
The overlay icon should be rendered regardless of icon alignment configuration.

**Screenshots**

Centered, icon missing - 2.5.3 ❌
![Screenshot 2024-11-12 at 3 36 08 PM](https://github.com/user-attachments/assets/0d32a8d1-1d69-43c6-ab89-5753f6a234b7)

Left, icon rendered - 2.5.3 ✅
![Screenshot 2024-11-12 at 3 36 48 PM](https://github.com/user-attachments/assets/8813a320-5c3b-473e-9a6b-ee520e60a297)

Centered, icon rendered - 2.5.2 check ✅
<img width="500" alt="Screenshot 2024-11-12 at 3 54 22 PM" src="https://github.com/user-attachments/assets/301fc673-488f-42d6-8777-d7fe1483ba64">

**Desktop (please complete the following information):**
 - macOS version: `Sequoia 15.1`
 - swiftDialog version: `swiftDialog 2.5.3`

**Additional context**
Apologies for the childish placeholder text.
I was tearing my hair out, taking screenshots for my own sanity until I realised it was a bug.

**Comment by in03** [comment]
Btw, I figured this out because I've been crafting up some initial script dialogs for [Baseline](https://github.com/SecondSonConsulting/Baseline). Things were fine for some time until they stopped rendering mid way through my testing. I realised Baseline can install the latest SwiftDialog as a post-run option and you'd just released 2.5.3 haha.

**Comment by in03** [comment]
Also, just realised that `bgcolour` option was passed incorrectly 🤦‍♂️

**Comment by bartreardon** [comment]
good catch

**Comment by bartreardon** [comment]
I've fixed this for cases where the number of icons is 1. If it's more than that then overlay icons won't show. I'll make sure to document this behaviour
