### ISSUE TITLE
Getting code 139 when I attempt to use the --timer function with --titlefont

### ISSUE THREAD

**Issue by TheFritz01** [swiftDialog/swiftDialog#47]
Whenever I try to setup a dialog that has both a timer and a custom --titlefont it never opens and returns error code 139. 

`58311 Segmentation fault: 11  "$dialog" --big --title "$title" --titlefont "colour=#009EDC,weight=medium,size=42" --message "$description" --icon "$icon" --timer 3600 --button1text "Continue" --button2text "Cancel"`

`Return: 139`

If I remove the --titlefont option the dialog will load with the timer just fine.

**Comment by TheFritz01** [comment]
I ran the same test dialog I have listed above 10 times in a row and it worked 8/10 times.  The two times it failed it returned the following:  (for reference, line 29 is the Cancel Button)  

`Untitled.sh: line 29: 31580 Segmentation fault: 11  "$dialog" --big --title "$title" --titlefont "colour=#009EDC,weight=medium,size=42" --message "$dialogMSG" --icon "$LOGOICNS" --timer 3600 --button1text "Continue" --button2text "Cancel"`

**Comment by bartreardon** [comment]
I've been unable to replicate the issue with the current build using the  examples above. 

The error itself I think is the outcome of trying to unwrap a nill optional but that should be consistent, not vary from run to run.

**Comment by bartreardon** [comment]
@TheFritz01  this should be resolved now with the latest build on the releases page.
