### ISSUE TITLE
Notifications no longer trigger action items from --button1action or --button2action on 2.5.4

### ISSUE THREAD

**Issue by philipross** [swiftDialog/swiftDialog#476]
**Describe the bug**
Using dialog to send System Notifications no longer trigger a configured action when using the `--button1action` and `--button2action` arguments

**To Reproduce**
1. Ensure `dialog -v` returns `2.5.4.4793`
2. Run: `dialog --notification --title "Test Notification" --message "Test notification for testing button actions" --button1text "Touch ID" --button1action "open x-apple.systempreference:com.apple.Touch-ID-Settings.extension" --button2text "Slack" --button2action "https://macadmins.slack.com/"`
3. Click on either of the action items. Button 1 should open the Touch ID System Settings extension. Button 2 should open the Mac Admins slack in your default brower.

**Expected behavior**
Button actions to trigger configured action.

**Desktop (please complete the following information):**
 - macOS version 15.2 (Beta)
 - swiftDialog version 2.5.4.4793

**Additional context**
Confirmed this works on dialog version 2.5.2.4777, and also on version 2.5.3.4785

**Comment by AirBookMac** [comment]
same here with macOS 15.1.1 and swiftDialog v2.5.4.4793

**Comment by AndiSchenk** [comment]
can confirm it is working with macOS 15.1.1 and swiftDialog 2.4.0.4750.
no longer works on 2.5.4.4793

**Comment by bartreardon** [comment]
thanks for the reports - I'll take a look

**Comment by AirBookMac** [comment]
v2.5.5b1 fixes this issue
https://github.com/swiftDialog/swiftDialog/releases/tag/v2.5.5b1

**Comment by bartreardon** [comment]
fixed in 2.5.5
