### ISSUE TITLE
Bug: `/usr/local/bin/dialog --help` shows `No argument found with the given name: none` and not help info

### ISSUE THREAD

**Issue by BigMacAdmin** [swiftDialog/swiftDialog#479]
**Describe the bug**
`/usr/local/bin/dialog --help` shows `No argument found with the given name: none` and not help info

**To Reproduce**
1. run the command above

**Expected behavior**
the excellent man page you've lovingly crafted should be printed 

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: 15.2
 - swiftDialog version: 2.5.4 and later (including 2.5.5 beta1)

**Additional context**
{Insert obsequious compliment here}

**Comment by wakco** [comment]
`dialog` by itself will act like `dialog --help` was entered, while `dialog --help` produces the error, however `dialog --help <option>` still works fine.
