### ISSUE TITLE
Error output when running with json input on Sequoia.

### ISSUE THREAD

**Issue by gilburns** [swiftDialog/swiftDialog#481]
**Describe the bug**
When running a command like this, there's extra error output:

`/usr/local/bin/dialog --jsonfile "/private/tmp/dialog_info.json"`

Error output looks like this:
```
2024-12-21 11:25:26.014 Dialog[10358:31487057] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-21 11:25:26.014 Dialog[10358:31487057] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```
If I use `2>/dev/null` at the end, it is properly redirected to null.

**To Reproduce**
1. Create a json file with your arguments
2. Run the command
3. Also happens if the json is passed directly with --jsonstring

**Expected behavior**
Should not have the error output. 😁 

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version:  15.2 (24C101)
 - swiftDialog version:  2.5.5.4802

**Additional context**
Not an issue that stops it from working, but a nice to fix?

**Comment by acodega** [comment]
I believe this is a Swiftism and not an error. I've seen it around for awhile any time I run swiftDialog. like it would happen with just this, `dialog --title "Hi there" --message "Welcome to the new beginning."` You shouldn't be getting it captured in output though that your script is grepping. Is that happening?

**Comment by gilburns** [comment]
You are right, I do see it happen with that other command, so it's not json only. 

Did some searching and it does appear this is a Sequoia bug in some Apple Private Frameworks, that lots of other people are complaining about. Sounds like I should just close this out and we just wait for Apple to address it.

https://discussions.apple.com/thread/255761734?sortBy=rank

https://github.com/zegervdv/homebrew-zathura/issues/129#issuecomment-2360382975

Thanks!
