### ISSUE TITLE
Add colour option for messages

### ISSUE THREAD

**Issue by FennaT** [swiftDialog/swiftDialog#53]
This application is awesome and makes Jamf Helper stink in comparison, but one thing I'd love to see is the option to change the colour of the main message.
In a similar way to what you've done with the title e.g. --titlefont "colour=#e2e2e2"

I appreciate messages currently only support markdown, which does not support colour. So perhaps implementing a second flag such as --messagefont which uses the same format as --titlefont would do the trick? Not sure if it would allow for splitting lines though.

For most applications Colour | Weight | Size is all I need.

The background feature is great, but without the ability to change the colour, only light images can be used. See below as an example:
![Screenshot 2021-10-15 at 15 14 07](https://user-images.githubusercontent.com/92585463/137492685-9dfd229d-ef55-490e-b35e-d09e56a5a5c4.png)

Totally understand if this isn't feasible to impliment though. Thanks!

**Comment by bartreardon** [comment]
@FennaT try this build with `--messagefont` and let me know what you think (`--help` should show all the supported options but essentially the same as `--titlefont` with some minor considerations )
[dialog-1.8.0-preview-1.zip](https://github.com/bartreardon/Dialog-public/files/7356557/dialog-1.8.0-preview-1.zip)

**Comment by bartreardon** [comment]
Can you replicate it with --debug flag and send me the output?

**Comment by bartreardon** [comment]
@FennaT can you try this build and let em know
[dialog.zip](https://github.com/bartreardon/Dialog-public/files/7378372/dialog.zip)
a

**Comment by bartreardon** [comment]
you're still going to have the problem I think - working on it

**Comment by bartreardon** [comment]
@FennaT this should be resolved now with the latest build on the releases page.
