### ISSUE TITLE
Investigate running at the login window

### ISSUE THREAD

**Issue by bartreardon** [swiftDialog/swiftDialog#68]
Had a request to see if we could get dialog running at the login window.

This is currently prevented because DNDPrefs lookup fails in that context

**Comment by shannonpasto** [comment]
Hi.

Just wondering how this is going? I'd like to have the ability to do fullscreen over the loginwindow (similar to jamfHelper). A bonus would be with dynamic text.

Cheers,
Shannon

**Comment by bartreardon** [comment]
low on the priority at the moment. sorting out the refactor for v2.0

**Comment by georgecm12** [comment]
This feature request would be extremely useful for displaying content on/over the login screen with fully unattended machines (labs, classrooms, digital signage, etc.) 

We are an .edu and running NoMAD Login AD strictly for its ability to have DEPNotify style dialogs over the login window. This allows us to send a student worker out to a class or lab with a brand new machine. On first boot, the Nomad Login AD screen requests the computer name from the student worker, after which it displays the status of the computer's provisioning (and secures the computer until provisioning is complete).

Running SwiftDialog at the login screen would allow us to retire that product in favor of something more modern, like Setup Your Mac.

**Comment by bartreardon** [comment]
@georgecm12 can you clarify if you mean the login window or the setup assistant?

**Comment by georgecm12** [comment]
@bartreardon Login Window.

Ideally, I would want to be able to have Jamf Pro tell the macOS to auto-advance through the setup assistant, then once it lands at the login window, display a Setup Your Mac screen over the login window without a user being logged in. That's the goal, at least! :)

**Comment by bartreardon** [comment]
Maybe but I'm not working on it. It likely won't work at all without a refactor of the code. As written, running at the login window and displaying a window is rather difficult.

**Comment by fraserhess** [comment]
I worked on this tonight and have swiftDialog running at the login window. I can't take too much credit. I applied the logic of [this post](https://github.com/fabienconus/zerouser/blob/main/zerotouch_zerouser_deployment.md) to swiftDialog and added a `--loginwindow` argument. It's about +20 lines including the help text.

I'm not sure of how to proceed from here.
1) Would you like a pull request? If so, branched from which branch?
1) I'm not sure how this feature should interact with other features

A login window screen shot:
![LWScreenShot 2024-01-26 at 9 51 13 PM](https://github.com/swiftDialog/swiftDialog/assets/57939/7486df28-6cf8-423b-b7df-909d682d98d2)

**Comment by bartreardon** [comment]
@fraserhess I would absolutely accept a PR. If you still have the code please submit it so you can be credited properly

In general, PR to main - I'll switch the branch as needed.

**Comment by fraserhess** [comment]
@bartreardon can probably close this now
