### ISSUE TITLE
FR: Add carousel view

### ISSUE THREAD

**Issue by WardsParadox** [swiftDialog/swiftDialog#70]
A carousel view to be able to display more info while tasks are occurring would be an awesome feature. I believe this can be sudo faked with a while loop writing to the command file, but it doesn't center up as nicely.

**Comment by bartreardon** [comment]
I've been thinking the same thing.

Passed in from a json file I was thinking something like:

```json
{
  "message" : [
    {"page1" : "Content here"},
    {"page2" : "Content here"},
    {"page3" : "Content here"}
  ]
}
```

and have the pages rotate around like they do with the image carosel. would need to think about how to make that updatable via command file.

**Comment by bartreardon** [comment]
probably not in my radar for a while so I'm going to close this as a wontfix

In the meantime, with the updated management of `--ontop` and `--blurscreen` when using multiple dialogs, a similar effect (from a UX point of view) can be done with some careful scripting. I've posted an example here which can be expanded on or pulled apart as needed.

https://github.com/bartreardon/swiftDialog-scripts/tree/main/MultiDialog
